### ISSUE TITLE
32-bit rr fails test exec_from_other_thread since 3875d7a5

### ISSUE THREAD

**Issue by bernhardu** [rr-debugger/rr#2924]
Hello, I tried to give a force32bit build a test run and found the exec_from_other_thread test failing.
Bisecting leads to 3875d7a5 / ff435c1f.
Around 1 of 4 runs of `rr record exec_from_other_thread` fail like below.
Gdb prints prev_task->pending_events has a value, but either this is not true, or this value is a null pointer?
Unfortunately I was not able to record rr itself in this situation successfully.
Is this the same what got described in # 2923 ?
```
$ bin/rr record bin/exec_from_other_thread
rr: Saving execution to trace directory `/.../rr/rr-recordings/exec_from_other_thread-200'.
........................................................................rr itself crashed (SIGSEGV). This shouldn't happen!
=== Start rr backtrace:
bin/rr(_ZN2rr13dump_rr_stackEv+0x3f)[0x56aa8dd7]
bin/rr(_ZN2rr15notifying_abortEv+0x6a)[0x56aa8d93]
bin/rr(+0x3b9f60)[0x56958f60]
linux-gate.so.1(__kernel_sigreturn+0x0)[0xf7f88570]
bin/rr(_ZNK2rr5Event4typeEv+0x10)[0x568921b6]
bin/rr(_ZN2rr13RecordSession11record_stepEv+0x11a)[0x56965c86]
bin/rr(+0x3ba986)[0x56959986]
bin/rr(_ZN2rr13RecordCommand3runERSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EE+0x3cd)[0x5695a605]
bin/rr(main+0x249)[0x56ac3ea8]
/lib/i386-linux-gnu/libc.so.6(__libc_start_main+0x106)[0xf793de46]
bin/rr(_start+0x31)[0x5684e681]
=== End rr backtrace
Abgebrochen (Speicherabzug geschrieben)

$ gdb -q -ex run --args bin/rr record bin/exec_from_other_thread
Reading symbols from bin/rr...
Starting program: /.../rr/2021-04-25/force32bit/obj/bin/rr record bin/exec_from_other_thread
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0xf7661b40 (LWP 150712)]
[New Thread 0xf61e4b40 (LWP 150713)]
[New Thread 0xf59e3b40 (LWP 150714)]
[New Thread 0xf51e2b40 (LWP 150715)]
[New Thread 0xf49e1b40 (LWP 150716)]
[New Thread 0xf41e0b40 (LWP 150717)]
[New Thread 0xf39dfb40 (LWP 150718)]
[New Thread 0xf31deb40 (LWP 150719)]
[New Thread 0xf29ddb40 (LWP 150720)]
[New Thread 0xf1ee5b40 (LWP 150721)]
[New Thread 0xf14ffb40 (LWP 150722)]
rr: Saving execution to trace directory `/.../rr/rr-recordings/exec_from_other_thread-204'.
[Detaching after fork from child process 150723]
.......................................................................................
Thread 1 "rr" received signal SIGSEGV, Segmentation fault.
0x568481b6 in rr::Event::type (this=0x0) at /.../rr/2021-04-25/rr/src/Event.h:345
345       EventType type() const { return event_type; }
(gdb) bt
#0  0x568481b6 in rr::Event::type (this=0x0) at /.../rr/2021-04-25/rr/src/Event.h:345
#1  0x5691bc86 in rr::RecordSession::record_step (this=0x56c74330) at /.../rr/2021-04-25/rr/src/RecordSession.cc:2341
#2  0x5690f986 in rr::record (args=std::vector of length 1, capacity 2 = {...}, flags=...) at /.../rr/2021-04-25/rr/src/RecordCommand.cc:656
#3  0x56910605 in rr::RecordCommand::run (this=0x56c6a120 <rr::RecordCommand::singleton>, args=std::vector of length 1, capacity 2 = {...})
    at /.../rr/2021-04-25/rr/src/RecordCommand.cc:791
#4  0x56a79ea8 in main (argc=3, argv=0xffffd174) at /.../rr/2021-04-25/rr/src/main.cc:249
(gdb) up
#1  0x5691bc86 in rr::RecordSession::record_step (this=0x56c74330) at /.../rr/2021-04-25/rr/src/RecordSession.cc:2341
2341      if (prev_task && prev_task->ev().type() == EV_SCHED) {
(gdb) print prev_task->pending_events
warning: can't find linker symbol for virtual table for `rr::RecordTask' value
$1 = std::deque with 1 element = {{event_type = 1455966496, {desched = {rec = {ptr = 1455865872}}, patch = {patch_after_syscall = 16, patch_vsyscall = 192}, signal = {siginfo = {si_signo = 1455865872, 
...
```

**Comment by rocallahan** [comment]
Does https://github.com/rr-debugger/rr/commit/d738c77fb65ced9971da4cd22ec37f545028f133 fix it?

**Comment by bernhardu** [comment]
Yes, now all tests pass again for a force32bit build running at a 64-bit kernel.
Thank you for the fast fix, I hope it is ok if I close this issue then.
