### ISSUE TITLE
rr replay stoped and does not worked as expect

### ISSUE THREAD

**Issue by kikimo** [rr-debugger/rr#3093]
My mozilla rr(compiled from the latest master branch) on ubuntu 20.04 cannot work as expected. It doesn't honor the breakpoint, and the stack is also broken I guess. Below is my execution sequence and output:

```txt
$ cat crand.c
#include <stdio.h>
#include <time.h>
#include <stdlib.h>

int main()
{
	int val = 0;

	srand(time(NULL));
	val = rand();
	printf("rand val: %d\n", val);

	return 0;
}

$ gcc crand.c -o rand -g
$ rr record ./rand
rr: Saving execution to trace directory `/root/.local/share/rr/rand-3'.
rand val: 273410699

$ rr replay
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /root/.local/share/rr/rand-3/mmap_clone_5_rand...
Really redefine built-in command "restart"? (y or n) [answered Y; input not from terminal]
Remote debugging using 127.0.0.1:25393
Reading symbols from /lib64/ld-linux-x86-64.so.2...
(No debugging symbols found in /lib64/ld-linux-x86-64.so.2)
0x00007ffff7fd0100 in ?? () from /lib64/ld-linux-x86-64.so.2
(rr) bt   # unexpected call stack
#0  0x00007ffff7fd0100 in ?? () from /lib64/ld-linux-x86-64.so.2
#1  0x0000000000000001 in ?? ()
#2  0x00007fffffffe61b in ?? ()
#3  0x0000000000000000 in ?? ()

(rr) l
1	#include <stdio.h>
2	#include <time.h>
3	#include <stdlib.h>
4
5	int main()
6	{
7		int val = 0;
8
9		srand(time(NULL));
10		val = rand();

(rr) b 9
Breakpoint 1 at 0x5555555551bc: file crand.c, line 9.

(rr) r
0x00007ffff7fd0103 in ?? () from /lib64/ld-linux-x86-64.so.2
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /root/.local/share/rr/rand-3/mmap_clone_5_rand

Program stopped.  # breakpoint not honored
0x00007ffff7fd0100 in ?? () from /lib64/ld-linux-x86-64.so.2

(rr) bt
#0  0x00007ffff7fd0100 in ?? () from /lib64/ld-linux-x86-64.so.2
#1  0x0000000000000001 in ?? ()
#2  0x00007fffffffe61b in ?? ()
#3  0x0000000000000000 in ?? ()
(rr)
```

**Comment by kikimo** [comment]
I almost forgot how to use rr after just a few months. Think this is the answer https://github.com/rr-debugger/rr/issues/1955:

>Don't run the binary when rr gives you the gdb prompt, continue it.

I'll just close this issue now.
