### ISSUE TITLE
Cannot opendir("/dev/dri/by-path")

### ISSUE THREAD

**Issue by aelovikov-intel** [rr-debugger/rr#3224]
```
$ cat a.c
#include <stdio.h>
#include <dirent.h>

int main() {
  DIR *dir = opendir("/dev/dri/by-path");
  if (dir == NULL) {
    puts("Failed to open");
    return 0;
  }
  puts("Opened");
  closedir(dir);
  return 0;
}

$ gcc a.c

$ ./a.out
Opened

$ rr ./a.out
rr: Saving execution to trace directory `<...>'.
Failed to open

$ rr --version
rr version 5.3.0
```

**Comment by Keno** [comment]
This is intentional. rr does not have support for recording interactions with graphics drivers, so dri is blacklisted (https://github.com/rr-debugger/rr/blob/9d623e8a92498d3f6e79eb3afb73a5ac6af3f5a3/src/preload/preload_interface.h#L596) to try and force software into CPU render fallbacks.

**Comment by aelovikov-intel** [comment]
Hi @Keno , thanks for such quick reply.

Is it possible to somehow ignore/mock/etc. the graphics part yet still being able to record the host/cpu execution?

It also says

> rr doesn't support DRI/DRM currently

Are there any plans for such support? I'd expect the answer is "no", but maybe I'm lucky today...

**Comment by Keno** [comment]
> Is it possible to somehow ignore/mock/etc.

You can comment out dri in the function I pointed out and see what happens.

> Are there any plans for such support? I'd expect the answer is "no", but maybe I'm lucky today...

I'd like to make that happen, but it's a fair bit of effort and not clear how well it'd work in the end.

**Comment by sahinf** [comment]
Hi, should this method work with Wayland compositors? I commented out the entire block that you linked but I still run into the same DRI error message when I try to `rr record -n` the sway window manager. 
Output of `gdb --args rr record -n sway-debug`:
```gdb
#0  0x000055555574f793 in rr::cpuid (code=0, subrequest=0) at /usr/src/debug/rr/rr-5.8.0/src/util.cc:842
#1  rr::cpuid_faulting_works () at /usr/src/debug/rr/rr-5.8.0/src/util.cc:1077
#2  0x00005555556623a9 in rr::Session::has_cpuid_faulting () at /usr/src/debug/rr/rr-5.8.0/src/Session.cc:740
#3  rr::RecordSession::create (argv=..., extra_env=..., disable_cpuid_features=..., syscallbuf=<optimized out>, 
    syscallbuf_desched_sig=<optimized out>, bind_cpu=<optimized out>, output_trace_dir=..., trace_id=<optimized out>, 
    use_audit=<optimized out>, unmap_vdso=<optimized out>, force_asan_active=<optimized out>, 
    force_tsan_active=<optimized out>, intel_pt=<optimized out>)
    at /usr/src/debug/rr/rr-5.8.0/src/RecordSession.cc:2493
#4  0x00005555556532f8 in rr::record (args=std::vector of length 1, capacity 4 = {...}, flags=...)
    at /usr/src/debug/rr/rr-5.8.0/src/RecordCommand.cc:684
#5  rr::RecordCommand::run (this=<optimized out>, args=std::vector of length 1, capacity 4 = {...})
    at /usr/src/debug/rr/rr-5.8.0/src/RecordCommand.cc:874
#6  0x00005555555a0518 in main (argc=<optimized out>, argv=<optimized out>)
    at /usr/src/debug/rr/rr-5.8.0/src/main.cc:278
(gdb) l

837     }
838
839     #if defined(__i386__) || defined(__x86_64__)
840     CPUIDData cpuid(uint32_t code, uint32_t subrequest) {
841       CPUIDData result;
842       asm volatile("cpuid"
843                    : "=a"(result.eax), "=b"(result.ebx), "=c"(result.ecx),
844                      "=d"(result.edx)
845                    : "a"(code), "c"(subrequest));
846       return result;
```

**Comment by sahinf** [comment]
I just need to reverse execute on a config load before the client is ready to be used so I didn't think the lack of DRI capabilities would matter. Got it to work by running the WM in headless mode.
