### ISSUE TITLE
zen_workaround.py input/output error

### ISSUE THREAD

**Issue by GitMensch** [rr-debugger/rr#3251]
```sh
$ sudo ../scripts/zen_workaround.py --check
Traceback (most recent call last):
  File "../scripts/zen_workaround.py", line 121, in <module>
    msrs = [read_msr(cpu) & BIT for cpu in cpus]
  File "../scripts/zen_workaround.py", line 121, in <listcomp>
    msrs = [read_msr(cpu) & BIT for cpu in cpus]
  File "../scripts/zen_workaround.py", line 58, in read_msr
    (val,) = struct.unpack('<q', os.read(msr, 8))
OSError: [Errno 5] Input/output error

$ uname -a
Linux instance-20220603-2334 5.4.17-2136.307.3.5.el8uek.x86_64 #2 SMP Thu May 26 18:17:42 PDT 2022 x86_64 x86_64 x86_64 GNU/Linux

$ cat /proc/cpuinfo
processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 23
model           : 1
model name      : AMD EPYC 7551 32-Core Processor
stepping        : 2
microcode       : 0x1000065
cpu MHz         : 1996.249
cache size      : 512 KB
physical id     : 0
siblings        : 2
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm rep_good nopl cpuid extd_apicid tsc_known_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext perfctr_core ssbd ibpb vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves nt_good clzero xsaveerptr virt_ssbd arat npt nrip_save arch_capabilities
bugs            : sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass
bogomips        : 3992.49
TLB size        : 1024 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:

# get zen workaround kernel module...
$ make
make -C /lib/modules/5.4.17-2136.307.3.5.el8uek.x86_64/build M=/home/opc/install/rr/build/module modules
make[1]: Entering directory '/usr/src/kernels/5.4.17-2136.307.3.5.el8uek.x86_64'
  CC [M]  /home/opc/install/rr/build/module/zen_workaround.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC [M]  /home/opc/install/rr/build/module/zen_workaround.mod.o
  LD [M]  /home/opc/install/rr/build/module/zen_workaround.ko
  BTF [M] /home/opc/install/rr/build/module/zen_workaround.ko
Skipping BTF generation for /home/opc/install/rr/build/module/zen_workaround.ko due to unavailability of vmlinux
make[1]: Leaving directory '/usr/src/kernels/5.4.17-2136.307.3.5.el8uek.x86_64'
$ echo $?
0
$ sudo insmod zen_workaround.ko

# re-running  zen_workaround.py --check has same issue
```

Is this failure during the check a sign that the zen workaround does not work?
If yes: would it be reasonable to try/catch this specific exception raising a message "you're out of luck, doesn't work"?

**Comment by rocallahan** [comment]
I don't know what `EIO` means for these MSRs. Maybe @glandium does?

**Comment by glandium** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/arch/x86/kernel/msr.c?id=e71e60cd74df9386c3f684c54888f2367050b831#n219

"MSR not supported", whatever that means. (lock-down, maybe?)

**Comment by glandium** [comment]
Mmmm that's on open, not read. The source for read doesn't have any code path that would return EIO...

**Comment by GitMensch** [comment]
H, I see that the failing line 58 https://github.com/rr-debugger/rr/blob/fceeeb4de042aa6064f86a7e31874ad001adf377/scripts/zen_workaround.py#L55-L60 is the "file" read; so the python `os.read()` maps to the kernel's `msr_read()`, correct? https://github.com/torvalds/linux/blob/219d54332a09e8d8741c1e1982f5eae56099de85/arch/x86/kernel/msr.c#L45-L71

How to verify that we're in that function?

**Comment by GitMensch** [comment]
Possibly the most reasonable thing from a user perspective is to try/catch `OSError`s in `read_msr()`.
Done with https://github.com/rr-debugger/rr/pull/3260.

Using this the python backtrace is gone, instead we get:

~~~
$ python zen_workaround.py
[Errno 13] Permission denied: '/dev/cpu/1/msr'Traceback (most recent call last):
  File "zen_workaround.py", line 82, in <module>
    msr = os.open('/dev/cpu/{}/msr'.format(cpu), os.O_WRONLY)
PermissionError: [Errno 13] Permission denied: '/dev/cpu/1/msr'
$ sudo python zen_workaround.py
[Errno 5] Input/output errorTraceback (most recent call last):
  File "zen_workaround.py", line 85, in <module>
    os.write(msr, struct.pack('<q', val))
OSError: [Errno 5] Input/output error
~~~
