### ISSUE TITLE
Locally observed replay divergence in setuid test

### ISSUE THREAD

**Issue by Keno** [rr-debugger/rr#3315]
Happens during the `getgrnam` call. During replay, the last nibble of this r10 register likes to jump around. Haven't tracked down yet where it's coming from, but given that it's inside nss, I'd expect perhaps some sort of shared memory cache we're not appropriately blocking.
```
[ERROR src/Registers.cc:295:maybe_print_reg_mismatch()] r10 0x5630dceb3148 != 0x5630dceb314a (replaying vs. recorded)
[FATAL src/Registers.cc:405:compare_register_files()] 
 (task 1831386 (rec:1830910) at time 357)
 -> Assertion `!bail_error || match' failed to hold. Fatal register mismatch (ticks/rec:162360/162360)
Tail of trace dump:
{
  real_time:11380153.407701 global_time:337, event:`SYSCALL: socket' (state:ENTERING_SYSCALL) tid:1830910, ticks:158216
rax:0xffffffffffffffda rbx:0x5630dcea8760 rcx:0xffffffffffffffff rdx:0x0 rsi:0x80801 rdi:0x1 rbp:0x5630dcea8860 rsp:0x7fff9c777108 r8:0x5630dceb1e20 r9:0x5630dcea8860 r10:0x5630dceb1ca0 r11:0x246 r12:0x2d r13:0x0 r14:0x5630dceb1e20 r15:0x7fff9c777160 rip:0x7f5155af87db eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x29 fs_base:0x7f51559d0b80 gs_base:0x0
}
{
  real_time:11380153.407731 global_time:338, event:`SYSCALL: socket' (state:EXITING_SYSCALL) tid:1830910, ticks:158216
rax:0x4 rbx:0x5630dcea8760 rcx:0xffffffffffffffff rdx:0x0 rsi:0x80801 rdi:0x1 rbp:0x5630dcea8860 rsp:0x7fff9c777108 r8:0x5630dceb1e20 r9:0x5630dcea8860 r10:0x5630dceb1ca0 r11:0x246 r12:0x2d r13:0x0 r14:0x5630dceb1e20 r15:0x7fff9c777160 rip:0x7f5155af87db eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x29 fs_base:0x7f51559d0b80 gs_base:0x0
}
{
  real_time:11380153.407828 global_time:339, event:`SYSCALL: connect' (state:ENTERING_SYSCALL) tid:1830910, ticks:158221
rax:0xffffffffffffffda rbx:0x5630dcea8760 rcx:0xffffffffffffffff rdx:0x2d rsi:0x7fff9c777160 rdi:0x4 rbp:0x5630dcea8860 rsp:0x7fff9c777108 r8:0x5630dceb1e20 r9:0x5630dcea8860 r10:0x5630dceb1ca0 r11:0x246 r12:0x2d r13:0x0 r14:0x5630dceb1e20 r15:0x7fff9c777160 rip:0x7f5155bdd507 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x2a fs_base:0x7f51559d0b80 gs_base:0x0
}
{
  real_time:11380153.410408 global_time:340, event:`SYSCALL: connect' (state:EXITING_SYSCALL) tid:1830910, ticks:158221
rax:0x0 rbx:0x5630dcea8760 rcx:0xffffffffffffffff rdx:0x2d rsi:0x7fff9c777160 rdi:0x4 rbp:0x5630dcea8860 rsp:0x7fff9c777108 r8:0x5630dceb1e20 r9:0x5630dcea8860 r10:0x5630dceb1ca0 r11:0x246 r12:0x2d r13:0x0 r14:0x5630dceb1e20 r15:0x7fff9c777160 rip:0x7f5155bdd507 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x2a fs_base:0x7f51559d0b80 gs_base:0x0
}
{
  real_time:11380153.410513 global_time:341, event:`SYSCALL: getpid' (state:ENTERING_SYSCALL) tid:1830910, ticks:158257
rax:0xffffffffffffffda rbx:0x5630dcea8780 rcx:0xffffffffffffffff rdx:0x5630dceb21b0 rsi:0xffffffff rdi:0x0 rbp:0x5630dceb1f00 rsp:0x7fff9c7770c8 r8:0x5630dcea8860 r9:0x5630dcea8780 r10:0x5630dceb1f00 r11:0x246 r12:0x0 r13:0x0 r14:0x5630dceb1e20 r15:0x7fff9c777160 rip:0x7f5155af076d eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x27 fs_base:0x7f51559d0b80 gs_base:0x0
}
{
  real_time:11380153.410541 global_time:342, event:`SYSCALL: getpid' (state:EXITING_SYSCALL) tid:1830910, ticks:158257
rax:0x1beffe rbx:0x5630dcea8780 rcx:0xffffffffffffffff rdx:0x5630dceb21b0 rsi:0xffffffff rdi:0x0 rbp:0x5630dceb1f00 rsp:0x7fff9c7770c8 r8:0x5630dcea8860 r9:0x5630dcea8780 r10:0x5630dceb1f00 r11:0x246 r12:0x0 r13:0x0 r14:0x5630dceb1e20 r15:0x7fff9c777160 rip:0x7f5155af076d eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x27 fs_base:0x7f51559d0b80 gs_base:0x0
}
{
  real_time:11380153.410640 global_time:343, event:`SYSCALL: epoll_create1' (state:ENTERING_SYSCALL) tid:1830910, ticks:158303
rax:0xffffffffffffffda rbx:0x5630dcea8780 rcx:0xffffffffffffffff rdx:0x21 rsi:0x0 rdi:0x80000 rbp:0x5630dceb1f00 rsp:0x7fff9c7770e8 r8:0x5630dceb21c0 r9:0x5630dcea8780 r10:0x5630dceb1f00 r11:0x246 r12:0x0 r13:0x0 r14:0x5630dceb1e20 r15:0x7fff9c777160 rip:0x7f5155af7afb eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x123 fs_base:0x7f51559d0b80 gs_base:0x0
}
{
  real_time:11380153.410669 global_time:344, event:`SYSCALL: epoll_create1' (state:EXITING_SYSCALL) tid:1830910, ticks:158303
rax:0x5 rbx:0x5630dcea8780 rcx:0xffffffffffffffff rdx:0x21 rsi:0x0 rdi:0x80000 rbp:0x5630dceb1f00 rsp:0x7fff9c7770e8 r8:0x5630dceb21c0 r9:0x5630dcea8780 r10:0x5630dceb1f00 r11:0x246 r12:0x0 r13:0x0 r14:0x5630dceb1e20 r15:0x7fff9c777160 rip:0x7f5155af7afb eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x123 fs_base:0x7f51559d0b80 gs_base:0x0
}
{
  real_time:11380153.410765 global_time:345, event:`SYSCALL: timerfd_create' (state:ENTERING_SYSCALL) tid:1830910, ticks:158491
rax:0xffffffffffffffda rbx:0x5630dcea8760 rcx:0xffffffffffffffff rdx:0xffffffff rsi:0x80800 rdi:0x1 rbp:0x5630dcea8860 rsp:0x7fff9c777108 r8:0x5630dceb1f00 r9:0x5630dcea8780 r10:0x5630dceb1f00 r11:0x246 r12:0x5630dceb1f70 r13:0x0 r14:0x5630dceb1e20 r15:0x7fff9c777160 rip:0x7f5155af7e8b eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x11b fs_base:0x7f51559d0b80 gs_base:0x0
}
{
  real_time:11380153.410794 global_time:346, event:`SYSCALL: timerfd_create' (state:EXITING_SYSCALL) tid:1830910, ticks:158491
rax:0x6 rbx:0x5630dcea8760 rcx:0xffffffffffffffff rdx:0xffffffff rsi:0x80800 rdi:0x1 rbp:0x5630dcea8860 rsp:0x7fff9c777108 r8:0x5630dceb1f00 r9:0x5630dcea8780 r10:0x5630dceb1f00 r11:0x246 r12:0x5630dceb1f70 r13:0x0 r14:0x5630dceb1e20 r15:0x7fff9c777160 rip:0x7f5155af7e8b eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x11b fs_base:0x7f51559d0b80 gs_base:0x0
}
{
  real_time:11380153.410889 global_time:347, event:`SYSCALL: epoll_ctl' (state:ENTERING_SYSCALL) tid:1830910, ticks:158495
rax:0xffffffffffffffda rbx:0x5630dcea8760 rcx:0xffffffffffffffff rdx:0x6 rsi:0x1 rdi:0x5 rbp:0x5630dcea8860 rsp:0x7fff9c777108 r8:0x5630dceb1f00 r9:0x5630dcea8780 r10:0x7fff9c777150 r11:0x246 r12:0x5630dceb1f70 r13:0x0 r14:0x5630dceb1e20 r15:0x7fff9c777160 rip:0x7f5155af7b2e eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xe9 fs_base:0x7f51559d0b80 gs_base:0x0
}
{
  real_time:11380153.410919 global_time:348, event:`SYSCALL: epoll_ctl' (state:EXITING_SYSCALL) tid:1830910, ticks:158495
rax:0x0 rbx:0x5630dcea8760 rcx:0xffffffffffffffff rdx:0x6 rsi:0x1 rdi:0x5 rbp:0x5630dcea8860 rsp:0x7fff9c777108 r8:0x5630dceb1f00 r9:0x5630dcea8780 r10:0x7fff9c777150 r11:0x246 r12:0x5630dceb1f70 r13:0x0 r14:0x5630dceb1e20 r15:0x7fff9c777160 rip:0x7f5155af7b2e eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xe9 fs_base:0x7f51559d0b80 gs_base:0x0
}
{
  real_time:11380153.411016 global_time:349, event:`SYSCALL: epoll_ctl' (state:ENTERING_SYSCALL) tid:1830910, ticks:158892
rax:0xffffffffffffffda rbx:0x5630dceb27d0 rcx:0xffffffffffffffff rdx:0x4 rsi:0x1 rdi:0x5 rbp:0x5630dcea8860 rsp:0x7fff9c7770d8 r8:0x5630dceb27d0 r9:0x5630dcea8780 r10:0x7fff9c7770ec r11:0x246 r12:0x4 r13:0x0 r14:0x5630dceb1e20 r15:0x7fff9c777160 rip:0x7f5155af7b2e eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xe9 fs_base:0x7f51559d0b80 gs_base:0x0
}
{
  real_time:11380153.411043 global_time:350, event:`SYSCALL: epoll_ctl' (state:EXITING_SYSCALL) tid:1830910, ticks:158892
rax:0x0 rbx:0x5630dceb27d0 rcx:0xffffffffffffffff rdx:0x4 rsi:0x1 rdi:0x5 rbp:0x5630dcea8860 rsp:0x7fff9c7770d8 r8:0x5630dceb27d0 r9:0x5630dcea8780 r10:0x7fff9c7770ec r11:0x246 r12:0x4 r13:0x0 r14:0x5630dceb1e20 r15:0x7fff9c777160 rip:0x7f5155af7b2e eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xe9 fs_base:0x7f51559d0b80 gs_base:0x0
}
{
  real_time:11380153.411155 global_time:351, event:`SYSCALL: clock_gettime' (state:ENTERING_SYSCALL) tid:1830910, ticks:161782
rax:0xffffffffffffffda rbx:0x5630dcea8760 rcx:0xffffffffffffffff rdx:0x0 rsi:0x7fff9c7770e0 rdi:0x1 rbp:0x1 rsp:0x7fff9c7770b8 r8:0x0 r9:0x7c r10:0x7f51559eb05a r11:0x246 r12:0x7fff9c7770e0 r13:0x0 r14:0x5630dceb1e20 r15:0x7fff9c777160 rip:0x6ffff030 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xe4 fs_base:0x7f51559d0b80 gs_base:0x0
}
{
  real_time:11380153.411190 global_time:352, event:`SYSCALL: clock_gettime' (state:EXITING_SYSCALL) tid:1830910, ticks:161782
rax:0x0 rbx:0x5630dcea8760 rcx:0xffffffffffffffff rdx:0x0 rsi:0x7fff9c7770e0 rdi:0x1 rbp:0x1 rsp:0x7fff9c7770b8 r8:0x0 r9:0x7c r10:0x7f51559eb05a r11:0x246 r12:0x7fff9c7770e0 r13:0x0 r14:0x5630dceb1e20 r15:0x7fff9c777160 rip:0x6ffff030 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xe4 fs_base:0x7f51559d0b80 gs_base:0x0
  { tid:1830910, addr:0x7fff9c7770e0, length:0x10 }
}
{
  real_time:11380153.411297 global_time:353, event:`SYSCALL: gettid' (state:ENTERING_SYSCALL) tid:1830910, ticks:162125
rax:0xffffffffffffffda rbx:0x5630dceb2d70 rcx:0xffffffffffffffff rdx:0xffffffff rsi:0x0 rdi:0x5630dceb2d70 rbp:0x1beffe rsp:0x7fff9c7770c8 r8:0x5630dceb2d70 r9:0x2 r10:0x7f51559eb05a r11:0x246 r12:0x0 r13:0x0 r14:0x5630dceb1e20 r15:0x7fff9c777160 rip:0x7f5155af809b eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xba fs_base:0x7f51559d0b80 gs_base:0x0
}
{
  real_time:11380153.411325 global_time:354, event:`SYSCALL: gettid' (state:EXITING_SYSCALL) tid:1830910, ticks:162125
rax:0x1beffe rbx:0x5630dceb2d70 rcx:0xffffffffffffffff rdx:0xffffffff rsi:0x0 rdi:0x5630dceb2d70 rbp:0x1beffe rsp:0x7fff9c7770c8 r8:0x5630dceb2d70 r9:0x2 r10:0x7f51559eb05a r11:0x246 r12:0x0 r13:0x0 r14:0x5630dceb1e20 r15:0x7fff9c777160 rip:0x7f5155af809b eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xba fs_base:0x7f51559d0b80 gs_base:0x0
}
{
  real_time:11380153.411422 global_time:355, event:`SYSCALL: futex' (state:ENTERING_SYSCALL) tid:1830910, ticks:162197
rax:0xffffffffffffffda rbx:0x7f51559a8060 rcx:0xffffffffffffffff rdx:0x7fffffff rsi:0x81 rdi:0x7f51559bb9a0 rbp:0x7f51559bb9a0 rsp:0x7fff9c7770a0 r8:0x8 r9:0x1 r10:0x0 r11:0x246 r12:0x7fff9c7770a0 r13:0x0 r14:0x5630dceb1e20 r15:0x7fff9c777160 rip:0x7f5155bdb4a7 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xca fs_base:0x7f51559d0b80 gs_base:0x0
}
{
  real_time:11380153.411450 global_time:356, event:`SYSCALL: futex' (state:EXITING_SYSCALL) tid:1830910, ticks:162197
rax:0x0 rbx:0x7f51559a8060 rcx:0xffffffffffffffff rdx:0x7fffffff rsi:0x81 rdi:0x7f51559bb9a0 rbp:0x7f51559bb9a0 rsp:0x7fff9c7770a0 r8:0x8 r9:0x1 r10:0x0 r11:0x246 r12:0x7fff9c7770a0 r13:0x0 r14:0x5630dceb1e20 r15:0x7fff9c777160 rip:0x7f5155bdb4a7 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xca fs_base:0x7f51559d0b80 gs_base:0x0
}
{
  real_time:11380153.411548 global_time:357, event:`SYSCALL: getdents64' (state:ENTERING_SYSCALL) tid:1830910, ticks:162360
rax:0xffffffffffffffda rbx:0x5630dcea9c90 rcx:0xffffffffffffffff rdx:0x8000 rsi:0x5630dcea9c90 rdi:0x3 rbp:0xffffffffffffff80 rsp:0x7fff9c7771f8 r8:0x90 r9:0x5630dcea8860 r10:0x5630dceb314a r11:0x246 r12:0x5630dcea9c64 r13:0x0 r14:0x5630dcea9c60 r15:0x0 rip:0x7f5155ab62eb eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xd9 fs_base:0x7f51559d0b80 gs_base:0x0
}
{
  real_time:11380153.411579 global_time:358, event:`SYSCALL: getdents64' (state:EXITING_SYSCALL) tid:1830910, ticks:162360
rax:0x0 rbx:0x5630dcea9c90 rcx:0xffffffffffffffff rdx:0x8000 rsi:0x5630dcea9c90 rdi:0x3 rbp:0xffffffffffffff80 rsp:0x7fff9c7771f8 r8:0x90 r9:0x5630dcea8860 r10:0x5630dceb314a r11:0x246 r12:0x5630dcea9c64 r13:0x0 r14:0x5630dcea9c60 r15:0x0 rip:0x7f5155ab62eb eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xd9 fs_base:0x7f51559d0b80 gs_base:0x0
  { tid:1830910, addr:0x5630dcea9c90, length:(nil) }
}
=== Start rr backtrace:
./bin/rr(_ZN2rr13dump_rr_stackEv+0x5d)[0x558be28b67a2]
./bin/rr(_ZN2rr9GdbServer15emergency_debugEPNS_4TaskE+0xf8)[0x558be26a901a]
./bin/rr(+0x3e9270)[0x558be26e3270]
./bin/rr(_ZN2rr21EmergencyDebugOstreamD1Ev+0x66)[0x558be26e34f8]
./bin/rr(_ZN2rr9Registers22compare_register_filesEPNS_10ReplayTaskEPKcRKS0_S4_S6_NS_16MismatchBehaviorE+0x149)[0x558be27e0323]
./bin/rr(_ZN2rr10ReplayTask13validate_regsEj+0x219)[0x558be2808ce7]
./bin/rr(+0x4f2a98)[0x558be27eca98]
./bin/rr(_ZN2rr13ReplaySession13enter_syscallEPNS_10ReplayTaskERKNS0_15StepConstraintsE+0x514)[0x558be27ecfcc]
./bin/rr(_ZN2rr13ReplaySession18try_one_trace_stepEPNS_10ReplayTaskERKNS0_15StepConstraintsE+0x127)[0x558be27f2031]
./bin/rr(_ZN2rr13ReplaySession11replay_stepERKNS0_15StepConstraintsE+0x1d7)[0x558be27f3897]
./bin/rr(_ZN2rr14ReplayTimeline19replay_step_forwardENS_10RunCommandE+0x11d)[0x558be2814853]
./bin/rr(_ZN2rr9GdbServer14debug_one_stepERNS_10GdbRequestE+0x71f)[0x558be26a5aaf]
./bin/rr(_ZN2rr9GdbServer12serve_replayERKNS0_15ConnectionFlagsE+0x5ab)[0x558be26a80e5]
./bin/rr(+0x4ede8b)[0x558be27e7e8b]
./bin/rr(_ZN2rr13ReplayCommand3runERSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EE+0x407)[0x558be27e8951]
./bin/rr(main+0x27d)[0x558be28d54ef]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7fda474a20b3]
./bin/rr(_start+0x2e)[0x558be25ef70e]
=== End rr backtrace
```

**Comment by rocallahan** [comment]
Yes, NSS is a known source of trouble.

**Comment by Keno** [comment]
Ok, finally managed to get dbgsysms installed. The backtrace of the function that returns diverging results is:
```
#0  0x00007f51559a2b38 in base_bucket_hash (h=0x5630dceb3140, p=0x5630dceb1e20) at ../src/basic/hashmap.c:347
#1  0x00007f51559960a4 in set_put (key=0x5630dceb1e20, s=<optimized out>) at ../src/basic/hashmap.c:1243
#2  userdb_connect (iterator=iterator@entry=0x5630dcea8760, 
    path=path@entry=0x5630dcea8860 "/run/systemd/userdb/io.systemd.DynamicUser", 
    method=method@entry=0x7f51559af318 "io.systemd.UserDatabase.GetGroupRecord", more=more@entry=false, 
    query=<optimized out>) at ../src/shared/userdb.c:366
#3  0x00007f515599c47e in userdb_start_query (iterator=iterator@entry=0x5630dcea8760, 
    method=method@entry=0x7f51559af318 "io.systemd.UserDatabase.GetGroupRecord", more=more@entry=false, 
    query=0x5630dcea88a0, flags=flags@entry=USERDB_AVOID_NSS) at ../src/shared/userdb.c:469
#4  0x00007f515599cbb5 in groupdb_by_name (name=0x5630dca4a036 "nobody", flags=USERDB_AVOID_NSS, ret=0x7fff9c7773b0)
    at ../src/shared/userdb.c:810
#5  0x00007f51559aa431 in userdb_getgrnam (errnop=<synthetic pointer>, buflen=2048, buffer=0x5630dcea8f90 "", 
    gr=0x7f5155bc7340 <resbuf>, name=0x5630dca4a036 "nobody") at ../src/nss-systemd/userdb-glue.c:18
#6  _nss_systemd_getgrnam_r (name=<optimized out>, gr=0x7f5155bc7340 <resbuf>, buffer=0x5630dcea8f90 "", buflen=2048, 
    errnop=0x7f51559d0b00) at ../src/nss-systemd/nss-systemd.c:217
#7  0x00007f5155ab852d in __getgrnam_r (name=name@entry=0x5630dca4a036 "nobody", 
    resbuf=resbuf@entry=0x7f5155bc7340 <resbuf>, buffer=0x5630dcea8f90 "", buflen=buflen@entry=2048, 
    result=result@entry=0x7fff9c777570) at ../nss/getXXbyYY_r.c:315
#8  0x00007f5155ab77dc in getgrnam (name=0x5630dca4a036 "nobody") at ../nss/getXXbyYY.c:134
#9  0x00005630dca4955e in main (argc=1, argv=0x7fff9c777708) at /home/keno/rr/src/test/setuid.c:15
```

**Comment by Keno** [comment]
Welp:
```
#0  rdrand (ret=ret@entry=0x7fff9c777060) at ../src/basic/random-util.c:101
#1  0x00007f51559a7e1b in genuine_random_bytes (
    flags=(RANDOM_EXTEND_WITH_PSEUDO | RANDOM_MAY_FAIL | RANDOM_ALLOW_RDRAND), n=16, p=0x7f51559bb990 <shared_hash_key>)
    at ../src/basic/random-util.c:183
#2  random_bytes (p=0x7f51559bb990 <shared_hash_key>, n=16) at ../src/basic/random-util.c:395
#3  0x00007f5155bdb47f in __pthread_once_slow (once_control=0x7f51559bb9a0 <once>, 
    init_routine=0x7f51559a8060 <shared_hash_key_initialize>) at pthread_once.c:116
#4  0x00007f5155bdb535 in __GI___pthread_once (once_control=once_control@entry=0x7f51559bb9a0 <once>, 
    init_routine=init_routine@entry=0x7f51559a8060 <shared_hash_key_initialize>) at pthread_once.c:143
#5  0x00007f51559a32f1 in hashmap_base_new (hash_ops=<optimized out>, type=<optimized out>) at ../src/basic/hashmap.c:799
#6  0x00007f51559963f1 in hashmap_base_ensure_allocated (type=HASHMAP_TYPE_SET, hash_ops=0x7f51559ba4e0 <link_hash_ops>, 
    h=0x5630dcea8768) at ../src/basic/hashmap.c:834
#7  internal_set_ensure_allocated (hash_ops=0x7f51559ba4e0 <link_hash_ops>, s=0x5630dcea8768)
    at ../src/basic/hashmap.c:851
#8  userdb_connect (iterator=iterator@entry=0x5630dcea8760, 
    path=path@entry=0x5630dcea8860 "/run/systemd/userdb/io.systemd.DynamicUser", 
    method=method@entry=0x7f51559af318 "io.systemd.UserDatabase.GetGroupRecord", more=more@entry=false, 
    query=<optimized out>) at ../src/shared/userdb.c:362
#9  0x00007f515599c47e in userdb_start_query (iterator=iterator@entry=0x5630dcea8760, 
    method=method@entry=0x7f51559af318 "io.systemd.UserDatabase.GetGroupRecord", more=more@entry=false, 
    query=0x5630dcea88a0, flags=flags@entry=USERDB_AVOID_NSS) at ../src/shared/userdb.c:469
#10 0x00007f515599cbb5 in groupdb_by_name (name=0x5630dca4a036 "nobody", flags=USERDB_AVOID_NSS, ret=0x7fff9c7773b0)
    at ../src/shared/userdb.c:810
#11 0x00007f51559aa431 in userdb_getgrnam (errnop=<synthetic pointer>, buflen=2048, buffer=0x5630dcea8f90 "", 
    gr=0x7f5155bc7340 <resbuf>, name=0x5630dca4a036 "nobody") at ../src/nss-systemd/userdb-glue.c:18
#12 _nss_systemd_getgrnam_r (name=<optimized out>, gr=0x7f5155bc7340 <resbuf>, buffer=0x5630dcea8f90 "", buflen=2048, 
    errnop=0x7f51559d0b00) at ../src/nss-systemd/nss-systemd.c:217
#13 0x00007f5155ab852d in __getgrnam_r (name=name@entry=0x5630dca4a036 "nobody", 
    resbuf=resbuf@entry=0x7f5155bc7340 <resbuf>, buffer=0x5630dcea8f90 "", buflen=buflen@entry=2048, 
    result=result@entry=0x7fff9c777570) at ../nss/getXXbyYY_r.c:315
#14 0x00007f5155ab77dc in getgrnam (name=0x5630dca4a036 "nobody") at ../nss/getXXbyYY.c:134
#15 0x00005630dca4955e in main (argc=1, argv=0x7fff9c777708) at /home/keno/rr/src/test/setuid.c:15
```

**Comment by Keno** [comment]
Argh, this is just #2694 and my systemd is just old. I feel stupid now.

**Comment by Keno** [comment]
We should probably consider a kernel patch to expose the CPUID patching capability on AMD, but I'm not really looking forward to the lkml discussion.
