### ISSUE TITLE
cdparanoia: Unsupported ioctl: SG_EMULATED_HOST

### ISSUE THREAD

**Issue by chkno** [rr-debugger/rr#3394]
Hi.  https://rr-project.org/ says "Please [file github issues](https://github.com/rr-debugger/rr/issues/) for unsupported system calls."  This is that.

I get `Fatal register mismatch` while trying to replay a cdparanoia run.  The mismatch is in a `write` syscall in which cdparanoia is reporting the result of its device probing: In the original run it prints `Drive is ATAPI (using SG_IO host adaptor emulation)` but in the replay it tries to print `Drive is SCSI`. cdparanoia does this device detection and printing in [interface/scsi_interface.c](https://svn.xiph.org/trunk/cdparanoia/interface/scsi_interface.c):

```c
  cdmessage(d,"\nChecking for SCSI emulation...\n");

  if (ioctl(fd,SG_EMULATED_HOST,&atapiret)){
    cderror(d,"\tSG_EMULATED_HOST ioctl() failed!\n");
    return(-1);
  } else {
    if(atapiret==1){
      if(d->interface == SGIO_SCSI){
	cdmessage(d,"\tDrive is ATAPI (using SG_IO host adaptor emulation)\n");
      }else if(d->interface == SGIO_SCSI_BUGGY1){
	cdmessage(d,"\tDrive is ATAPI (using SG_IO host adaptor emulation with workarounds)\n");
      }else{
	cdmessage(d,"\tDrive is ATAPI (using SCSI host adaptor emulation)\n");
	/* Disable kernel SCSI command translation layer for access through sg */
	if (ioctl(fd,SG_SET_TRANSFORM,0))
	  cderror(d,"\tCouldn't disable kernel command translation layer\n");
      }
      d->is_atapi=1;
    }else{
      cdmessage(d,"\tDrive is SCSI\n");
      d->is_atapi=0;
    }
```

I get `Fatal register mismatch` trying to replay cdparanoia runs in rr versions 5.5.0, 5.6.0, and HEAD (currently 0b5d4fedfe9ae0ad53b527adb041cc1e8dcf7f83).

Log of attempt at HEAD (currently 0b5d4fedfe9ae0ad53b527adb041cc1e8dcf7f83):

```
$ $(nix-build --expr 'with import <nixpkgs-unstable> {}; rr.overrideAttrs (old: { src = builtins.fetchGit { url = "https://github.com/rr-debugger/rr.git"; rev = "0b5d4fedfe9ae0ad53b527adb041cc1e8dcf7f83"; }; })')/bin/rr record $(nix-build --expr 'with import <nixpkgs-unstable> {}; enableDebugging cdparanoia')/bin/cdparanoia --verbose --batch
rr: Saving execution to trace directory `/home/user/.local/share/rr/cdparanoia-1'.
cdparanoia III release 10.2 (September 11, 2008)

Using cdda library version: 10.2
Using paranoia library version: 10.2
Checking /dev/cdrom for cdrom...
        Testing /dev/cdrom for SCSI/MMC interface
                SG_IO device: /dev/sr0

CDROM model sensed sensed: HL-DT-ST BD-RE  WH14NS40 1.03


Checking for SCSI emulation...
        Drive is ATAPI (using SG_IO host adaptor emulation)

Checking for MMC style command set...
        Drive is MMC style
        DMA scatter/gather table entries: 1
        table entry size: 131072 bytes
        maximum theoretical transfer: 55 sectors
        Setting default read size to 27 sectors (63504 bytes).

Verifying CDDA command set...
        Expected command set reads OK.

Attempting to set cdrom to full speed...
        drive returned OK.

Table of contents (audio tracks only):
...<truncated>...

$ $(nix-build --expr 'with import <nixpkgs-unstable> {}; rr.overrideAttrs (old: { src = builtins.fetchGit { url = "https://github.com/rr-debugger/rr.git"; rev = "0b5d4fedfe9ae0ad53b527adb041cc1e8dcf7f83"; }; })')/bin/rr replay
GNU gdb (GDB) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /nix/store/lqg51b6m35n3wac8j2js585zgsgm9bfg-cdparanoia-III-10.2/bin/cdparanoia...
Really redefine built-in command "restart"? (y or n) [answered Y; input not from terminal]
Really redefine built-in command "jump"? (y or n) [answered Y; input not from terminal]
Remote debugging using 127.0.0.1:31237
Reading symbols from /nix/store/c6f52mvbv0d8rd3rlslsvy7v4g3pmm7p-glibc-2.35-163/lib/ld-linux-x86-64.so.2...
(No debugging symbols found in /nix/store/c6f52mvbv0d8rd3rlslsvy7v4g3pmm7p-glibc-2.35-163/lib/ld-linux-x86-64.so.2)
0x00007fa2e4af2300 in _start () from /nix/store/c6f52mvbv0d8rd3rlslsvy7v4g3pmm7p-glibc-2.35-163/lib/ld-linux-x86-64.so.2
(rr) continue
Continuing.
cdparanoia III release 10.2 (September 11, 2008)

Using cdda library version: 10.2
Using paranoia library version: 10.2
Checking /dev/cdrom for cdrom...
        Testing /dev/cdrom for SCSI/MMC interface
                SG_IO device: /dev/sr0

CDROM model sensed sensed: HL-DT-ST BD-RE  WH14NS40 1.03


Checking for SCSI emulation...
[ERROR src/Registers.cc:295:maybe_print_reg_mismatch()] rdx 0xf != 0x35 (replaying vs. recorded)
[ERROR src/Registers.cc:295:maybe_print_reg_mismatch()] rsi 0x7fa2e4abb785 != 0x7fa2e4abb100 (replaying vs. recorded)
[FATAL src/Registers.cc:405:compare_register_files()]
 (task 293382 (rec:291850) at time 485)
 -> Assertion `!bail_error || match' failed to hold. Fatal register mismatch (ticks/rec:82955/82957)
Tail of trace dump:
{
  real_time:8943858.891605 global_time:465, event:`SYSCALLBUF_RESET' tid:291850, ticks:82340
}
{
  real_time:8943858.891652 global_time:466, event:`SYSCALL: ioctl' (state:EXITING_SYSCALL) tid:291850, ticks:82340
rax:0x0 rbx:0x7ffd7c795db0 rcx:0xffffffffffffffff rdx:0x7ffd7c795d60 rsi:0x5382 rdi:0x3 rbp:0x3 rsp:0x7ffd7c795cf0 r8:0x3 r9:0x0 r10:0x0 r11:0x246 r12:0xc2a330 r13:0x1 r14:0x0 r15:0xc2a7b0 rip:0x7fa2e48b72e1 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x10 fs_base:0x7fa2e47a7c40 gs_base:0x0
}
{
  real_time:8943858.891721 global_time:467, event:`SYSCALL: ioctl' (state:ENTERING_SYSCALL) tid:291850, ticks:82343
rax:0xffffffffffffffda rbx:0x7ffd7c795db0 rcx:0xffffffffffffffff rdx:0x7ffd7c795d5c rsi:0x5386 rdi:0x3 rbp:0x3 rsp:0x7ffd7c795cf0 r8:0x3 r9:0x0 r10:0x0 r11:0x246 r12:0x0 r13:0x1 r14:0x0 r15:0xc2a7b0 rip:0x7fa2e48b72e1 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x10 fs_base:0x7fa2e47a7c40 gs_base:0x0
}
{
  real_time:8943858.891770 global_time:468, event:`SYSCALL: ioctl' (state:EXITING_SYSCALL) tid:291850, ticks:82343
rax:0x0 rbx:0x7ffd7c795db0 rcx:0xffffffffffffffff rdx:0x7ffd7c795d5c rsi:0x5386 rdi:0x3 rbp:0x3 rsp:0x7ffd7c795cf0 r8:0x3 r9:0x0 r10:0x0 r11:0x246 r12:0x0 r13:0x1 r14:0x0 r15:0xc2a7b0 rip:0x7fa2e48b72e1 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x10 fs_base:0x7fa2e47a7c40 gs_base:0x0
}
{
  real_time:8943858.891839 global_time:469, event:`SYSCALLBUF_FLUSH' tid:291850, ticks:82389
  { syscall:'clock_gettime', ret:0x0, size:0x20 }
}
{
  real_time:8943858.891856 global_time:470, event:`SYSCALL: ioctl' (state:ENTERING_SYSCALL) tid:291850, ticks:82389
rax:0xffffffffffffffda rbx:0xc2a330 rcx:0xffffffffffffffff rdx:0x7ffd7c795c90 rsi:0x2285 rdi:0x3 rbp:0x0 rsp:0x7ffd7c795bc0 r8:0x38 r9:0xff r10:0x0 r11:0x246 r12:0x2285 r13:0x3 r14:0x7ffd7c795c90 r15:0x7ffd7c795d70 rip:0x7fa2e48b72e1 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x10 fs_base:0x7fa2e47a7c40 gs_base:0x0
}
{
  real_time:8943858.891866 global_time:471, event:`SYSCALLBUF_RESET' tid:291850, ticks:82389
}
{
  real_time:8943858.893235 global_time:472, event:`SYSCALL: ioctl' (state:EXITING_SYSCALL) tid:291850, ticks:82389
rax:0x0 rbx:0xc2a330 rcx:0xffffffffffffffff rdx:0x7ffd7c795c90 rsi:0x2285 rdi:0x3 rbp:0x0 rsp:0x7ffd7c795bc0 r8:0x38 r9:0xff r10:0x0 r11:0x246 r12:0x2285 r13:0x3 r14:0x7ffd7c795c90 r15:0x7ffd7c795d70 rip:0x7fa2e48b72e1 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x10 fs_base:0x7fa2e47a7c40 gs_base:0x0
  { tid:291850, addr:0x7ffd7c795c90, length:0x58 }
  { tid:291850, addr:0xc2a7d0, length:0x38 }
  { tid:291850, addr:0x7ffd7c795d70, length:0x10 }
}
{
  real_time:8943858.893304 global_time:473, event:`SYSCALLBUF_FLUSH' tid:291850, ticks:82742
  { syscall:'clock_gettime', ret:0x0, size:0x20 }
}
{
  real_time:8943858.893315 global_time:474, event:`SYSCALL: write' (state:ENTERING_SYSCALL) tid:291850, ticks:82742
rax:0xffffffffffffffda rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x3b rsi:0xc3a860 rdi:0x2 rbp:0x681ffe60 rsp:0x681ffe00 r8:0x7fa2e4964f40 r9:0x0 r10:0x0 r11:0x246 r12:0x1 r13:0x0 r14:0xc3a860 r15:0xc2a7d0 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x1 fs_base:0x7fa2e47a7c40 gs_base:0x0
}
{
  real_time:8943858.893325 global_time:475, event:`SYSCALLBUF_RESET' tid:291850, ticks:82742
}
{
  real_time:8943858.893380 global_time:476, event:`SYSCALL: write' (state:EXITING_SYSCALL) tid:291850, ticks:82742
rax:0x3b rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x3b rsi:0xc3a860 rdi:0x2 rbp:0x681ffe60 rsp:0x681ffe00 r8:0x7fa2e4964f40 r9:0x0 r10:0x0 r11:0x246 r12:0x1 r13:0x0 r14:0xc3a860 r15:0xc2a7d0 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x1 fs_base:0x7fa2e47a7c40 gs_base:0x0
}
{
  real_time:8943858.893501 global_time:477, event:`SYSCALL: write' (state:ENTERING_SYSCALL) tid:291850, ticks:82809
rax:0xffffffffffffffda rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x1 rsi:0x7fa2e49ae543 rdi:0x2 rbp:0x681ffe60 rsp:0x681ffe00 r8:0x7 r9:0xc3a860 r10:0xcc2e09b4aff9c1c4 r11:0x246 r12:0x1 r13:0x7fa2e49ae4c0 r14:0x7fa2e49a9840 r15:0x1 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x1 fs_base:0x7fa2e47a7c40 gs_base:0x0
}
{
  real_time:8943858.893554 global_time:478, event:`SYSCALL: write' (state:EXITING_SYSCALL) tid:291850, ticks:82809
rax:0x1 rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x1 rsi:0x7fa2e49ae543 rdi:0x2 rbp:0x681ffe60 rsp:0x681ffe00 r8:0x7 r9:0xc3a860 r10:0xcc2e09b4aff9c1c4 r11:0x246 r12:0x1 r13:0x7fa2e49ae4c0 r14:0x7fa2e49a9840 r15:0x1 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x1 fs_base:0x7fa2e47a7c40 gs_base:0x0
}
{
  real_time:8943858.893677 global_time:479, event:`SYSCALL: write' (state:ENTERING_SYSCALL) tid:291850, ticks:82863
rax:0xffffffffffffffda rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x1 rsi:0x7fa2e49ae543 rdi:0x2 rbp:0x681ffe60 rsp:0x681ffe00 r8:0x7 r9:0xc3a860 r10:0xcc2e09b4aff9c1c4 r11:0x246 r12:0x1 r13:0x7fa2e49ae4c0 r14:0x7fa2e49a9840 r15:0x1 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x1 fs_base:0x7fa2e47a7c40 gs_base:0x0
}
{
  real_time:8943858.893729 global_time:480, event:`SYSCALL: write' (state:EXITING_SYSCALL) tid:291850, ticks:82863
rax:0x1 rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x1 rsi:0x7fa2e49ae543 rdi:0x2 rbp:0x681ffe60 rsp:0x681ffe00 r8:0x7 r9:0xc3a860 r10:0xcc2e09b4aff9c1c4 r11:0x246 r12:0x1 r13:0x7fa2e49ae4c0 r14:0x7fa2e49a9840 r15:0x1 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x1 fs_base:0x7fa2e47a7c40 gs_base:0x0
}
{
  real_time:8943858.893850 global_time:481, event:`SYSCALL: write' (state:ENTERING_SYSCALL) tid:291850, ticks:82916
rax:0xffffffffffffffda rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x20 rsi:0x7fa2e4abb0b0 rdi:0x2 rbp:0x681ffe60 rsp:0x681ffe00 r8:0x7 r9:0xc3a860 r10:0xcc2e09b4aff9c1c4 r11:0x246 r12:0xdf r13:0x0 r14:0x0 r15:0x0 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x1 fs_base:0x7fa2e47a7c40 gs_base:0x0
}
{
  real_time:8943858.893902 global_time:482, event:`SYSCALL: write' (state:EXITING_SYSCALL) tid:291850, ticks:82916
rax:0x20 rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x20 rsi:0x7fa2e4abb0b0 rdi:0x2 rbp:0x681ffe60 rsp:0x681ffe00 r8:0x7 r9:0xc3a860 r10:0xcc2e09b4aff9c1c4 r11:0x246 r12:0xdf r13:0x0 r14:0x0 r15:0x0 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x1 fs_base:0x7fa2e47a7c40 gs_base:0x0
}
{
  real_time:8943858.894026 global_time:483, event:`SYSCALL: ioctl' (state:ENTERING_SYSCALL) tid:291850, ticks:82920
rax:0xffffffffffffffda rbx:0xc2a330 rcx:0xffffffffffffffff rdx:0x7ffd7c795f84 rsi:0x2203 rdi:0x4 rbp:0x4 rsp:0x7ffd7c795f20 r8:0x7 r9:0xc3a860 r10:0xcc2e09b4aff9c1c4 r11:0x246 r12:0xdf r13:0x0 r14:0x0 r15:0x0 rip:0x7fa2e48b72e1 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x10 fs_base:0x7fa2e47a7c40 gs_base:0x0
}
{
  real_time:8943858.894088 global_time:484, event:`SYSCALL: ioctl' (state:EXITING_SYSCALL) tid:291850, ticks:82920
rax:0x0 rbx:0xc2a330 rcx:0xffffffffffffffff rdx:0x7ffd7c795f84 rsi:0x2203 rdi:0x4 rbp:0x4 rsp:0x7ffd7c795f20 r8:0x7 r9:0xc3a860 r10:0xcc2e09b4aff9c1c4 r11:0x246 r12:0xdf r13:0x0 r14:0x0 r15:0x0 rip:0x7fa2e48b72e1 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x10 fs_base:0x7fa2e47a7c40 gs_base:0x0
}
{
  real_time:8943858.894155 global_time:485, event:`SYSCALL: write' (state:ENTERING_SYSCALL) tid:291850, ticks:82957
rax:0xffffffffffffffda rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x35 rsi:0x7fa2e4abb100 rdi:0x2 rbp:0x681ffe60 rsp:0x681ffe00 r8:0x7 r9:0xc3a860 r10:0xcc2e09b4aff9c1c4 r11:0x246 r12:0xdf r13:0x0 r14:0x0 r15:0x0 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x1 fs_base:0x7fa2e47a7c40 gs_base:0x0
}
{
  real_time:8943858.894249 global_time:486, event:`SYSCALL: write' (state:EXITING_SYSCALL) tid:291850, ticks:82957
rax:0x35 rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x35 rsi:0x7fa2e4abb100 rdi:0x2 rbp:0x681ffe60 rsp:0x681ffe00 r8:0x7 r9:0xc3a860 r10:0xcc2e09b4aff9c1c4 r11:0x246 r12:0xdf r13:0x0 r14:0x0 r15:0x0 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x1 fs_base:0x7fa2e47a7c40 gs_base:0x0
}
=== Start rr backtrace:
/nix/store/iciq30657zp0aswc69w81g99j1cj4gkj-rr-5.6.0/bin/rr(_ZN2rr13dump_rr_stackEv+0x47)[0x9ea627]
/nix/store/iciq30657zp0aswc69w81g99j1cj4gkj-rr-5.6.0/bin/rr(_ZN2rr9GdbServer15emergency_debugEPNS_4TaskE+0xf7)[0x7f667f]
/nix/store/iciq30657zp0aswc69w81g99j1cj4gkj-rr-5.6.0/bin/rr[0x82e901]
/nix/store/iciq30657zp0aswc69w81g99j1cj4gkj-rr-5.6.0/bin/rr(_ZN2rr21EmergencyDebugOstreamD1Ev+0x5f)[0x82eb93]
/nix/store/iciq30657zp0aswc69w81g99j1cj4gkj-rr-5.6.0/bin/rr(_ZN2rr9Registers22compare_register_filesEPNS_10ReplayTaskEPKcRKS0_S4_S6_NS_16MismatchBehaviorE+0x154)[0x92005e]
/nix/store/iciq30657zp0aswc69w81g99j1cj4gkj-rr-5.6.0/bin/rr(_ZN2rr10ReplayTask13validate_regsEj+0x22a)[0x946110]
/nix/store/iciq30657zp0aswc69w81g99j1cj4gkj-rr-5.6.0/bin/rr[0x92abc2]
/nix/store/iciq30657zp0aswc69w81g99j1cj4gkj-rr-5.6.0/bin/rr(_ZN2rr13ReplaySession13enter_syscallEPNS_10ReplayTaskERKNS0_15StepConstraintsE+0x3f2)[0x92afd0]
/nix/store/iciq30657zp0aswc69w81g99j1cj4gkj-rr-5.6.0/bin/rr(_ZN2rr13ReplaySession18try_one_trace_stepEPNS_10ReplayTaskERKNS0_15StepConstraintsE+0x122)[0x9300de]
/nix/store/iciq30657zp0aswc69w81g99j1cj4gkj-rr-5.6.0/bin/rr(_ZN2rr13ReplaySession11replay_stepERKNS0_15StepConstraintsE+0x1d3)[0x931929]
/nix/store/iciq30657zp0aswc69w81g99j1cj4gkj-rr-5.6.0/bin/rr(_ZN2rr14ReplayTimeline19replay_step_forwardENS_10RunCommandE+0xd4)[0x9510c4]
/nix/store/iciq30657zp0aswc69w81g99j1cj4gkj-rr-5.6.0/bin/rr(_ZN2rr9GdbServer14debug_one_stepERNS_10GdbRequestE+0x67f)[0x7f3539]
/nix/store/iciq30657zp0aswc69w81g99j1cj4gkj-rr-5.6.0/bin/rr(_ZN2rr9GdbServer12serve_replayERKNS0_15ConnectionFlagsE+0x55d)[0x7f582b]
/nix/store/iciq30657zp0aswc69w81g99j1cj4gkj-rr-5.6.0/bin/rr[0x92623b]
/nix/store/iciq30657zp0aswc69w81g99j1cj4gkj-rr-5.6.0/bin/rr(_ZN2rr13ReplayCommand3runERSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EE+0x436)[0x926c2e]
/nix/store/iciq30657zp0aswc69w81g99j1cj4gkj-rr-5.6.0/bin/rr(main+0x286)[0xa0bc26]
/nix/store/c6f52mvbv0d8rd3rlslsvy7v4g3pmm7p-glibc-2.35-163/lib/libc.so.6(+0x2924e)[0x7f053f00124e]
/nix/store/c6f52mvbv0d8rd3rlslsvy7v4g3pmm7p-glibc-2.35-163/lib/libc.so.6(__libc_start_main+0x89)[0x7f053f001309]
/nix/store/iciq30657zp0aswc69w81g99j1cj4gkj-rr-5.6.0/bin/rr(_start+0x25)[0x7495c5]
=== End rr backtrace
Launch gdb with
  gdb '-l' '10000' '-ex' 'set sysroot /' '-ex' 'target extended-remote 127.0.0.1:31238' /nix/store/lqg51b6m35n3wac8j2js585zgsgm9bfg-cdparanoia-III-10.2/bin/cdparanoia
```

Attaching gdb as directed shows that it's trying to print `Drive is SCSI`:

```
$ gdb '-l' '10000' '-ex' 'set sysroot /' '-ex' 'target extended-remote 127.0.0.1:31238' /nix/store/lqg51b6m35n3wac8j2js585zgsgm9bfg-cdparanoia-III-10.2/bin/cdparanoia
GNU gdb (GDB) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /nix/store/lqg51b6m35n3wac8j2js585zgsgm9bfg-cdparanoia-III-10.2/bin/cdparanoia...
Remote debugging using 127.0.0.1:31238
Reading symbols from /nix/store/iciq30657zp0aswc69w81g99j1cj4gkj-rr-5.6.0/bin/../lib/rr/librrpreload.so...
(No debugging symbols found in /nix/store/iciq30657zp0aswc69w81g99j1cj4gkj-rr-5.6.0/bin/../lib/rr/librrpreload.so)
Reading symbols from /nix/store/lqg51b6m35n3wac8j2js585zgsgm9bfg-cdparanoia-III-10.2/lib/libcdda_interface.so.0...
Reading symbols from /nix/store/lqg51b6m35n3wac8j2js585zgsgm9bfg-cdparanoia-III-10.2/lib/libcdda_paranoia.so.0...
Reading symbols from /nix/store/c6f52mvbv0d8rd3rlslsvy7v4g3pmm7p-glibc-2.35-163/lib/libm.so.6...
(No debugging symbols found in /nix/store/c6f52mvbv0d8rd3rlslsvy7v4g3pmm7p-glibc-2.35-163/lib/libm.so.6)
Reading symbols from /nix/store/c6f52mvbv0d8rd3rlslsvy7v4g3pmm7p-glibc-2.35-163/lib/librt.so.1...
(No debugging symbols found in /nix/store/c6f52mvbv0d8rd3rlslsvy7v4g3pmm7p-glibc-2.35-163/lib/librt.so.1)
Reading symbols from /nix/store/c6f52mvbv0d8rd3rlslsvy7v4g3pmm7p-glibc-2.35-163/lib/libc.so.6...
(No debugging symbols found in /nix/store/c6f52mvbv0d8rd3rlslsvy7v4g3pmm7p-glibc-2.35-163/lib/libc.so.6)
Reading symbols from /nix/store/c6f52mvbv0d8rd3rlslsvy7v4g3pmm7p-glibc-2.35-163/lib/libdl.so.2...
(No debugging symbols found in /nix/store/c6f52mvbv0d8rd3rlslsvy7v4g3pmm7p-glibc-2.35-163/lib/libdl.so.2)
Reading symbols from /nix/store/c6f52mvbv0d8rd3rlslsvy7v4g3pmm7p-glibc-2.35-163/lib/libpthread.so.0...
(No debugging symbols found in /nix/store/c6f52mvbv0d8rd3rlslsvy7v4g3pmm7p-glibc-2.35-163/lib/libpthread.so.0)
Reading symbols from /nix/store/c6f52mvbv0d8rd3rlslsvy7v4g3pmm7p-glibc-2.35-163/lib/ld-linux-x86-64.so.2...
(No debugging symbols found in /nix/store/c6f52mvbv0d8rd3rlslsvy7v4g3pmm7p-glibc-2.35-163/lib/ld-linux-x86-64.so.2)
0x0000000070000002 in ?? ()
(gdb) bt
#0  0x0000000070000002 in ?? ()
#1  0x00007fa2e4ac77a6 in _raw_syscall () from /nix/store/iciq30657zp0aswc69w81g99j1cj4gkj-rr-5.6.0/bin/../lib/rr/librrpreload.so
#2  0x00007fa2e4ac1b25 in traced_raw_syscall () from /nix/store/iciq30657zp0aswc69w81g99j1cj4gkj-rr-5.6.0/bin/../lib/rr/librrpreload.so
#3  0x00007fa2e4ac68f8 in sys_write () from /nix/store/iciq30657zp0aswc69w81g99j1cj4gkj-rr-5.6.0/bin/../lib/rr/librrpreload.so
#4  0x00007fa2e4ac75b7 in syscall_hook_internal () from /nix/store/iciq30657zp0aswc69w81g99j1cj4gkj-rr-5.6.0/bin/../lib/rr/librrpreload.so
#5  0x00007fa2e4ac769e in syscall_hook () from /nix/store/iciq30657zp0aswc69w81g99j1cj4gkj-rr-5.6.0/bin/../lib/rr/librrpreload.so
#6  0x00007fa2e4ac10e3 in _syscall_hook_trampoline () from /nix/store/iciq30657zp0aswc69w81g99j1cj4gkj-rr-5.6.0/bin/../lib/rr/librrpreload.so
#7  0x00007fa2e4ac114d in __morestack () from /nix/store/iciq30657zp0aswc69w81g99j1cj4gkj-rr-5.6.0/bin/../lib/rr/librrpreload.so
#8  0x00007fa2e4ac1169 in _syscall_hook_trampoline_48_3d_00_f0_ff_ff ()
   from /nix/store/iciq30657zp0aswc69w81g99j1cj4gkj-rr-5.6.0/bin/../lib/rr/librrpreload.so
#9  0x00007fa2e48b169d in write () from /nix/store/c6f52mvbv0d8rd3rlslsvy7v4g3pmm7p-glibc-2.35-163/lib/libc.so.6
#10 0x00007fa2e4ab4075 in cdmessage (d=d@entry=0xc2a330, s=s@entry=0x7fa2e4abb785 "\tDrive is SCSI\n")
    at /build/cdparanoia-III-10.2/interface/utils.h:124
#11 0x00007fa2e4ab5d99 in check_atapi (d=d@entry=0xc2a330) at scsi_interface.c:1613
#12 0x00007fa2e4ab77b3 in scsi_init_drive (d=d@entry=0xc2a330) at scsi_interface.c:1682
#13 0x00007fa2e4ab381a in cdda_open (d=0xc2a330) at interface.c:61
#14 0x00000000004046e2 in main (argc=3, argv=0x7ffd7c796cf8) at main.c:1021
(gdb)

**Comment by chkno** [comment]
Ah, I found RR_LOG:

```
Checking for SCSI emulation...
[record_syscall] 9565: processing: SYSCALL: write -- time: 482
[record_syscall] handling ioctl(0x2203): type:0x22 nr:0x3 dir:0 size:0
[record_syscall]   (presumed ignorable ioctl, nothing to do)
[record_syscall] 9565: processing: SYSCALL: ioctl -- time: 484
        Drive is ATAPI (using SG_IO host adaptor emulation)
```

SG_EMULATED_HOST is 0x2203.  rr says it presumes it is ignorable.  It isn't ignorable.

Adding special handling for this ioctl solves the problem!

```diff
--- a/src/record_syscall.cc
+++ b/src/record_syscall.cc
@@ -1816,6 +1816,7 @@ static Switchable prepare_ioctl(RecordTask* t,
       syscall_state.reg_parameter<typename Arch::hci_dev_list_req>(3);
       return PREVENT_SWITCH;
 
+    case SG_EMULATED_HOST:
     case SG_GET_VERSION_NUM:
       syscall_state.reg_parameter<typename Arch::signed_int>(3);
       return PREVENT_SWITCH;
```

... but then cddparanoia invokes more ioctls that need similar treatment: SG_SET_RESERVED_SIZE and SG_GET_SG_TABLESIZE.

I'm making progress figuring out how to add support for these.  I'll report back when I have the whole list or get stuck...

**Comment by khuey** [comment]
Yeah that diff looks correct for SG_EMULATED_HOST, but you'll need to do everything that program needs. Let us know if you get stuck somewhere or need help.

**Comment by chkno** [comment]
Thanks!

Oh, easy, looks like there were only two more.  I created PR https://github.com/rr-debugger/rr/pull/3395
