### ISSUE TITLE
Firefox doesn't run on latest master, possibly only when glibc is older

### ISSUE THREAD

**Issue by julienw** [rr-debugger/rr#3427]
Hey,
I updated rr to latest master, and then Firefox wouldn't launch.
So I bisected and found this commit to be the likely culprit:
https://github.com/rr-debugger/rr/commit/2c3e53506bd650b5ae7876e2bd4fa4e17255b2b7

This makes some sense because I'm using Debian stable where glibc is v2.31. On @padenot's machine on the other hand everything works fine, his glibc is v2.36.

Hopefully this information will help you find the issue. Hit me up on matrix (julienw) if you want me to try something.

**Comment by khuey** [comment]
When you say it won't launch what precisely does that mean? Does it crash? Exit silently?

**Comment by padenot** [comment]
It waits for ever on a `waitpid(...)` call, @julienw can probably get detailed info.

**Comment by khuey** [comment]
Ok. Does the same thing happen with `record -n`?

**Comment by julienw** [comment]
Yes the same thing happens with `record -n`.

This is waiting on rr itself. Here is the end of running with strace:
```
openat(AT_FDCWD, "/home/julien/travail/git/mozilla-central/testing/mozbase/mozdebug/mozdebug/__pycache__/__init__.cpython-39.pyc", O_RDONLY|O_CLOEXEC) = 6
fstat(6, {st_mode=S_IFREG|0644, st_size=882, ...}) = 0
ioctl(6, TCGETS, 0x7ffd72da8900)        = -1 ENOTTY (Ioctl() inapproprié pour un périphérique)
lseek(6, 0, SEEK_CUR)                   = 0
lseek(6, 0, SEEK_CUR)                   = 0
fstat(6, {st_mode=S_IFREG|0644, st_size=882, ...}) = 0
read(6, "a\r\r\n\0\0\0\0\214G\305c\212\3\0\0\343\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 883) = 882
read(6, "", 1)                          = 0
close(6)                                = 0
stat("/home/julien/travail/git/mozilla-central/testing/mozbase/mozdebug/mozdebug", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/home/julien/travail/git/mozilla-central/testing/mozbase/mozdebug/mozdebug", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/home/julien/travail/git/mozilla-central/testing/mozbase/mozdebug/mozdebug", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
openat(AT_FDCWD, "/home/julien/travail/git/mozilla-central/testing/mozbase/mozdebug/mozdebug", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 6
fstat(6, {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
getdents64(6, 0x286b7d0 /* 5 entries */, 32768) = 144
getdents64(6, 0x286b7d0 /* 0 entries */, 32768) = 0
close(6)                                = 0
stat("/home/julien/travail/git/mozilla-central/testing/mozbase/mozdebug/mozdebug/mozdebug.py", {st_mode=S_IFREG|0755, st_size=10983, ...}) = 0
stat("/home/julien/travail/git/mozilla-central/testing/mozbase/mozdebug/mozdebug/mozdebug.py", {st_mode=S_IFREG|0755, st_size=10983, ...}) = 0
openat(AT_FDCWD, "/home/julien/travail/git/mozilla-central/testing/mozbase/mozdebug/mozdebug/__pycache__/mozdebug.cpython-39.pyc", O_RDONLY|O_CLOEXEC) = 6
fstat(6, {st_mode=S_IFREG|0644, st_size=5427, ...}) = 0
ioctl(6, TCGETS, 0x7ffd72da7ad0)        = -1 ENOTTY (Ioctl() inapproprié pour un périphérique)
lseek(6, 0, SEEK_CUR)                   = 0
lseek(6, 0, SEEK_CUR)                   = 0
fstat(6, {st_mode=S_IFREG|0644, st_size=5427, ...}) = 0
read(6, "a\r\r\n\0\0\0\0\214G\305c\347*\0\0\343\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 5428) = 5427
read(6, "", 1)                          = 0
close(6)                                = 0
stat("rr", 0x7ffd72da8fd0)              = -1 ENOENT (Aucun fichier ou dossier de ce type)
stat("/home/julien/.mozbuild/srcdirs/mozilla-central-b880089790d1/_virtualenvs/mach/bin/rr", 0x7ffd72da8fd0) = -1 ENOENT (Aucun fichier ou dossier de ce type)
stat("/home/julien/.local/bin/rr", 0x7ffd72da8fd0) = -1 ENOENT (Aucun fichier ou dossier de ce type)
stat("/home/julien/bin/rr", 0x7ffd72da8fd0) = -1 ENOENT (Aucun fichier ou dossier de ce type)
stat("/home/julien/.nvm/versions/node/v16.19.0/bin/rr", 0x7ffd72da8fd0) = -1 ENOENT (Aucun fichier ou dossier de ce type)
stat("/home/julien/.cargo/bin/rr", 0x7ffd72da8fd0) = -1 ENOENT (Aucun fichier ou dossier de ce type)
stat("/usr/local/bin/rr", {st_mode=S_IFREG|0755, st_size=65247520, ...}) = 0
getpid()                                = 533469
write(1, "\33[34m 0:00.84\33(B\33[m /usr/local/b"..., 324 0:00.84 /usr/local/bin/rr record -n --disable-avx-512 --disable-cpuid-features-ext 0xfc230000,0x2c42,0xc /home/julien/travail/git/mozilla-central/obj-x86_64-pc-linux-gnu-opt/dist/bin/firefox -no-remote -profile /home/julien/travail/git/mozilla-central/obj-x86_64-pc-linux-gnu-opt/tmp/profile-default
) = 324
write(5, "[1674668161.0446293, \"new_proces"..., 341) = 341
getpid()                                = 533469
write(5, "[1674668161.044949, \"process\", {"..., 4822) = 4822
getrandom("\xd6\x80\x01\xf7\xf0\x34\x30\x2c\x9c\x37\xbb\x2f\xdf\x37\x38\x38", 16, 0) = 16
getrandom("\xcd\xca\x68\x51\x10\x5c\xba\xdd\x4d\x0c\x8c\x61\x3f\x42\x25\xb4", 16, 0) = 16
mmap(NULL, 36864, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7f13b80a9000
rt_sigprocmask(SIG_BLOCK, ~[], [], 8)   = 0
clone(child_stack=0x7f13b80b1ff0, flags=CLONE_VM|CLONE_VFORK|SIGCHLD) = 533533
munmap(0x7f13b80a9000, 36864)           = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
getrandom("\x5a\x95\xa8\x6a\xd5\x6d\x34\x6c\x8d\x3c\xac\x30\x1c\x58\x5e\x47", 16, 0) = 16
getrandom("\x96\x98\xeb\x7e\x72\x74\x52\x1b\x71\x12\x87\x79\x02\x19\x21\x1c", 16, 0) = 16
wait4(533533, rr: Saving execution to trace directory `/home/julien/.local/share/rr/firefox-16'.
```
Hope this helps

**Comment by julienw** [comment]
`533533` is the pid of the rr process

**Comment by khuey** [comment]
I think I see this too with Ubuntu 20.04 and glibc 2.31.

```
{
  real_time:3665206.582627 global_time:25350, event:`SYSCALL: wait4' (state:EXITING_SYSCALL) tid:59287, ticks:625915042
rax:0xfffffffffffffe00 rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x0 rsi:0x7ffe904ffd1c rdi:0xe7c0 rbp:0x681fffa0 rsp:0x681ffd40 r8:0x0 r9:0x80000000 r10:0x0 r11:0x246 r12:0xe7c0 r13:0x0 r14:0x7fe583e98e00 r15:0x7fe5831a61d0 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x3d fs_base:0x7fe584b80740 gs_base:0x0
}
{
  real_time:3665206.582708 global_time:25351, event:`SIGNAL: SIGCHLD(async)' tid:59287, ticks:625915042
rax:0xfffffffffffffe00 rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x0 rsi:0x7ffe904ffd1c rdi:0xe7c0 rbp:0x681fffa0 rsp:0x681ffd40 r8:0x0 r9:0x80000000 r10:0x0 r11:0x246 r12:0xe7c0 r13:0x0 r14:0x7fe583e98e00 r15:0x7fe5831a61d0 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x3d fs_base:0x7fe584b80740 gs_base:0x0 st0:0x0 st1:0x0 st2:0x0 st3:0x0 st4:0x0 st5:0x0 st6:0x0 st7:0x0 ymm0:0x3a3a3a3a3a3a3a3a3a3a3a3a3a3a3a3a ymm1:0xff000000ff00000000000000000000 ymm2:0xff00000000000000000000 ymm3:0x0 ymm4:0x0 ymm5:0x0 ymm6:0x0 ymm7:0x0 ymm8:0x613a4f697c006b636f6c206572697571 ymm9:0x0 ymm10:0x40220fd21b95825b ymm11:0x4000000000000000 ymm12:0x90ca10000000000090ca10 ymm13:0x90ca10 ymm14:0x909fe0000000000090ca10 ymm15:0x909fe0
}
{
  real_time:3665206.582804 global_time:25352, event:`SIGNAL_DELIVERY: SIGCHLD(async)' tid:59287, ticks:625915042
rax:0x3d rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x0 rsi:0x7ffe904ffd1c rdi:0xe7c0 rbp:0x681fffa0 rsp:0x681ffd40 r8:0x0 r9:0x80000000 r10:0x0 r11:0x246 r12:0xe7c0 r13:0x0 r14:0x7fe583e98e00 r15:0x7fe5831a61d0 rip:0x70000000 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x3d fs_base:0x7fe584b80740 gs_base:0x0
}
{
  real_time:3665206.582884 global_time:25353, event:`SYSCALL: restart_syscall' (state:ENTERING_SYSCALL) tid:59287, ticks:625915042
rax:0xffffffffffffffda rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x0 rsi:0x7ffe904ffd1c rdi:0xe7c0 rbp:0x681fffa0 rsp:0x681ffd40 r8:0x0 r9:0x80000000 r10:0x0 r11:0x246 r12:0xe7c0 r13:0x0 r14:0x7fe583e98e00 r15:0x7fe5831a61d0 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x3d fs_base:0x7fe584b80740 gs_base:0x0
}
{
  real_time:3665224.915990 global_time:25354, event:`SYSCALL: restart_syscall' (state:EXITING_SYSCALL) tid:59287, ticks:625915042
rax:0xfffffffffffffe00 rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x0 rsi:0x7ffe904ffd1c rdi:0xe7c0 rbp:0x681fffa0 rsp:0x681ffd40 r8:0x0 r9:0x80000000 r10:0x0 r11:0x246 r12:0xe7c0 r13:0x0 r14:0x7fe583e98e00 r15:0x7fe5831a61d0 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x3d fs_base:0x7fe584b80740 gs_base:0x0
}
{
  real_time:3665224.916727 global_time:25355, event:`SIGNAL: SIGINT(async)' tid:59287, ticks:625915042
rax:0xfffffffffffffe00 rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x0 rsi:0x7ffe904ffd1c rdi:0xe7c0 rbp:0x681fffa0 rsp:0x681ffd40 r8:0x0 r9:0x80000000 r10:0x0 r11:0x246 r12:0xe7c0 r13:0x0 r14:0x7fe583e98e00 r15:0x7fe5831a61d0 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x3d fs_base:0x7fe584b80740 gs_base:0x0 st0:0x0 st1:0x0 st2:0x0 st3:0x0 st4:0x0 st5:0x0 st6:0x0 st7:0x0 ymm0:0x3a3a3a3a3a3a3a3a3a3a3a3a3a3a3a3a ymm1:0xff000000ff00000000000000000000 ymm2:0xff00000000000000000000 ymm3:0x0 ymm4:0x0 ymm5:0x0 ymm6:0x0 ymm7:0x0 ymm8:0x613a4f697c006b636f6c206572697571 ymm9:0x0 ymm10:0x40220fd21b95825b ymm11:0x4000000000000000 ymm12:0x90ca10000000000090ca10 ymm13:0x90ca10 ymm14:0x909fe0000000000090ca10 ymm15:0x909fe0
}
```

You can see where I killed it at 25355.

**Comment by khuey** [comment]
Reverting 2c3e53506bd650b5ae7876e2bd4fa4e17255b2b7 does indeed make it go away.

**Comment by khuey** [comment]
The new code is triggering allocator reentry.

```
0x00007f7615623170 in __lll_lock_wait () from /lib/x86_64-linux-gnu/libpthread.so.0
(rr) bt
#0  0x00007f7615623170 in __lll_lock_wait () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f761561b235 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x000056402bffdbba in Mutex::Lock (this=0x56402c09dc88 <gInitLock>)
    at /home/khuey/dev/gecko-dev/memory/build/Mutex.h:123
#3  AutoLock<Mutex>::AutoLock (aMutex=..., this=<optimized out>) at /home/khuey/dev/gecko-dev/memory/build/Mutex.h:183
#4  malloc_init_hard () at /home/khuey/dev/gecko-dev/memory/build/mozjemalloc.cpp:4167
#5  malloc_init () at /home/khuey/dev/gecko-dev/memory/build/mozjemalloc.cpp:1436
#6  0x000056402c002695 in BaseAllocator::calloc (this=<optimized out>, aNum=<optimized out>, aSize=<optimized out>)
    at /home/khuey/dev/gecko-dev/memory/build/mozjemalloc.cpp:4410
#7  Allocator<MozJemallocBase>::calloc (arg1=94833616739464, arg2=128)
    at /home/khuey/dev/gecko-dev/memory/build/malloc_decls.h:52
#8  0x00007f7615634c05 in ?? () from /lib/x86_64-linux-gnu/libdl.so.2
#9  0x00007f7615634525 in dlsym () from /lib/x86_64-linux-gnu/libdl.so.2
#10 0x00007f761566db03 in pthread_mutex_init (mutex=0x56402c09e450 <chunks_mtx>, attr=<optimized out>)
    at /home/khuey/dev/rr/src/preload/overrides.c:97
#11 0x000056402bffde93 in Mutex::Init (this=<optimized out>) at /home/khuey/dev/gecko-dev/memory/build/Mutex.h:64
#12 malloc_init_hard () at /home/khuey/dev/gecko-dev/memory/build/mozjemalloc.cpp:4291
#13 malloc_init () at /home/khuey/dev/gecko-dev/memory/build/mozjemalloc.cpp:1436
#14 0x000056402c002d41 in Allocator<MozJemallocBase>::jemalloc_stats_internal (aStats=0x56402c09dc88 <gInitLock>, 
    aBinStats=0x80) at /home/khuey/dev/gecko-dev/memory/build/mozjemalloc.cpp:4559
#15 0x000056402c01b268 in phc_init (aMallocTable=0x7ffe2ddd26e8, aBridge=0x56402c09e300 <gReplaceMallocBridge>)
    at /home/khuey/dev/gecko-dev/memory/replace/phc/PHC.cpp:1549
#16 0x000056402bffcca4 in init () at /home/khuey/dev/gecko-dev/memory/build/mozjemalloc.cpp:5001
#17 0x000056402bffcd3b in Allocator<ReplaceMallocBase>::malloc (arg1=72704)
    at /home/khuey/dev/gecko-dev/memory/build/malloc_decls.h:51
#18 malloc (arg1=72704) at /home/khuey/dev/gecko-dev/memory/build/malloc_decls.h:51
#19 0x00007f76154d4a9a in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#20 0x00007f761568cb9a in ?? () from /lib64/ld-linux-x86-64.so.2
#21 0x00007f761568cca1 in ?? () from /lib64/ld-linux-x86-64.so.2
#22 0x00007f761567c13a in ?? () from /lib64/ld-linux-x86-64.so.2
#23 0x0000000000000004 in ?? ()
#24 0x00007ffe2ddd2e63 in ?? ()
#25 0x00007ffe2ddd2eac in ?? ()
#26 0x00007ffe2ddd2eb7 in ?? ()
#27 0x00007ffe2ddd2ec0 in ?? ()
#28 0x0000000000000000 in ?? ()
```

**Comment by julienw** [comment]
Thanks, latest master works fine!
