### ISSUE TITLE
Firefox ASan builds fail to launch

### ISSUE THREAD

**Issue by tysmith** [rr-debugger/rr#3445]
The browser crashes during launch or just shortly after.

I've narrowed it down to commit 143ebdd. Everything works as expected with the previous commit 140d3cf.

The command I used to launch is:
`rr record --chaos --disable-cpuid-features-ext 0xdc230000,0x2c42,0xc ./firefox -no-remote -headless`

I am able to reproduce the issue and I'd be happy to test patches.

Here is an example of a an ASan error I'm seeing:
```
AddressSanitizer: CHECK failed: sanitizer_allocator_primary64.h:845 "((region->allocated_meta)) <= ((region->mapped_meta))" (0x1, 0x0) (tid=190414)
    #0 0x55ed396eacc1 in __asan::CheckUnwind() /builds/worker/fetches/llvm-project/compiler-rt/lib/asan/asan_rtl.cpp:69:3
    #1 0x55ed39702e54 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /builds/worker/fetches/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_termination.cpp:86:5
    #2 0x55ed396651a3 in __sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView>>::PopulateFreeArray(__sanitizer::AllocatorStats*, unsigned long, __sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView>>::RegionInfo*, unsigned long) /builds/worker/fetches/llvm-project/compiler-rt/lib/asan/../sanitizer_common/sanitizer_allocator_primary64.h:845:5
    #3 0x55ed39664d20 in __sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView>>::GetFromAllocator(__sanitizer::AllocatorStats*, unsigned long, unsigned int*, unsigned long) /builds/worker/fetches/llvm-project/compiler-rt/lib/asan/../sanitizer_common/sanitizer_allocator_primary64.h:220:11
    #4 0x55ed396648c2 in __sanitizer::SizeClassAllocator64LocalCache<__sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView>>>::Refill(__sanitizer::SizeClassAllocator64LocalCache<__sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView>>>::PerClass*, __sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView>>*, unsigned long) /builds/worker/fetches/llvm-project/compiler-rt/lib/asan/../sanitizer_common/sanitizer_allocator_local_cache.h:103:9
    #5 0x55ed39664563 in Allocate /builds/worker/fetches/llvm-project/compiler-rt/lib/asan/../sanitizer_common/sanitizer_allocator_local_cache.h:39:11
    #6 0x55ed39664563 in __sanitizer::CombinedAllocator<__sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView>>, __sanitizer::LargeMmapAllocatorPtrArrayDynamic>::Allocate(__sanitizer::SizeClassAllocator64LocalCache<__sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView>>>*, unsigned long, unsigned long) /builds/worker/fetches/llvm-project/compiler-rt/lib/asan/../sanitizer_common/sanitizer_allocator_combined.h:69:20
    #7 0x55ed3966048e in __asan::Allocator::Allocate(unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType, bool) /builds/worker/fetches/llvm-project/compiler-rt/lib/asan/asan_allocator.cpp:526:29
    #8 0x55ed3965e4e9 in Calloc /builds/worker/fetches/llvm-project/compiler-rt/lib/asan/asan_allocator.cpp:736:17
    #9 0x55ed3965e4e9 in __asan::asan_calloc(unsigned long, unsigned long, __sanitizer::BufferedStackTrace*) /builds/worker/fetches/llvm-project/compiler-rt/lib/asan/asan_allocator.cpp:957:34
    #10 0x55ed396e160b in calloc /builds/worker/fetches/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:78:10
    #11 0x7f77134b631c in _dl_check_map_versions /build/glibc-SzIz7B/glibc-2.31/elf/dl-version.c:274:2
    #12 0x7f77134b90fc in dl_open_worker /build/glibc-SzIz7B/glibc-2.31/elf/dl-open.c:577:14
    #13 0x7f7713649927 in _dl_catch_exception /build/glibc-SzIz7B/glibc-2.31/elf/dl-error-skeleton.c:208:8
    #14 0x7f77134b8609 in _dl_open /build/glibc-SzIz7B/glibc-2.31/elf/dl-open.c:837:17
    #15 0x55ed3a4cb34b in dlopen_doit /build/glibc-SzIz7B/glibc-2.31/dlfcn/dlopen.c:66:15
    #16 0x7f7713649927 in _dl_catch_exception /build/glibc-SzIz7B/glibc-2.31/elf/dl-error-skeleton.c:208:8
    #17 0x7f77136499f2 in _dl_catch_error /build/glibc-SzIz7B/glibc-2.31/elf/dl-error-skeleton.c:227:19
    #18 0x55ed3a4cbb58 in _dlerror_run /build/glibc-SzIz7B/glibc-2.31/dlfcn/dlerror.c:170:21
    #19 0x55ed3a4cb3d9 in dlopen /build/glibc-SzIz7B/glibc-2.31/dlfcn/dlopen.c:87:10
    #20 0x55ed396b375c in dlopen /builds/worker/fetches/llvm-project/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:6537:15
    #21 0x55ed3972f978 in GetLibHandle(char const*) /builds/worker/checkouts/gecko/xpcom/glue/standalone/nsXPCOMGlue.cpp:89:29
    #22 0x55ed3972f146 in ReadDependentCB(char const*, mozilla::LibLoadingStrategy) /builds/worker/checkouts/gecko/xpcom/glue/standalone/nsXPCOMGlue.cpp:144:3
    #23 0x55ed3972dd3a in XPCOMGlueLoad(char const*, mozilla::LibLoadingStrategy) /builds/worker/checkouts/gecko/xpcom/glue/standalone/nsXPCOMGlue.cpp:323:9
    #24 0x55ed3972cb92 in mozilla::GetBootstrap(char const*, mozilla::LibLoadingStrategy) /builds/worker/checkouts/gecko/xpcom/glue/standalone/nsXPCOMGlue.cpp:405:3
    #25 0x55ed3971f0d0 in InitXPCOMGlue(mozilla::LibLoadingStrategy) /builds/worker/checkouts/gecko/browser/app/nsBrowserApp.cpp:241:7
    #26 0x55ed3971ea6c in main /builds/worker/checkouts/gecko/browser/app/nsBrowserApp.cpp:348:19
    #27 0x7f771350d082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
    #28 0x55ed3965ca98 in _start (/home/twsmith/workspace/browsers/m-c-20230222094403-fuzzing-asan-noopt/firefox+0x196a98) (BuildId: 0d026760e19ea6f6709d62263dca3c7c606410d8)
```

**Comment by khuey** [comment]
Is there a reason you're not using the `--asan` flag too?

**Comment by tysmith** [comment]
No reason. Is it safe to use with non-asan builds? We don't know what type of build we will be running with.

**Comment by khuey** [comment]
It will disturb execution (by constraining which parts of the address space the build can use) but I don't think it is unsafe.

I can reproduce all sorts of ASAN freakouts without the --asan flag but Firefox seems to start up ok with it.

**Comment by tysmith** [comment]
Using `--asan` does not seem to help.

**Comment by khuey** [comment]
Just to be sure, you're passing `--asan` to `rr record`, not to `firefox`, right?

**Comment by tysmith** [comment]
Yes :)

**Comment by khuey** [comment]
Hmm, ok. I can reproduce the issue without --asan but not with it. You're still seeing the original issue? Can you submit a recording of it to Pernosco?

**Comment by tysmith** [comment]
I have submitted a recording.

**Comment by tysmith** [comment]
I am also seeing this from time to time (seems related). I am running this on a machine with 64GB of memory with <1GB in use.

```
Launch command: rr record --asan --chaos --disable-cpuid-features-ext 0xdc230000,0x2c42,0xc /home/user/workspace/browsers/m-c-20230222094403-fuzzing-asan-noopt/firefox -no-remote -headless
```
```

[FATAL src/AutoRemoteSyscalls.cc:785:check_syscall_result()] 
 (task 866039 (rec:866039) at time 772)
 -> Assertion `false' failed to hold. Syscall mmap failed with errno ENOMEM
Tail of trace dump:
{
  real_time:420866.651782 global_time:752, event:`PATCH_SYSCALL' tid:866037, ticks:1109725
rax:0xba rbx:0x46192ddab000 rcx:0xffffffffffffffff rdx:0x1adc126e3340 rsi:0x1 rdi:0x10 rbp:0x7ffe57122230 rsp:0x7ffe571219d8 r8:0x46192ddab000 r9:0x1 r10:0xefffffffffffffff r11:0x246 r12:0x561baa85b8e0 r13:0x0 r14:0x7ffe57122280 r15:0x7ffe57122260 rip:0x561baa684085 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xffffffffffffffff fs_base:0x7f5420425400 gs_base:0x0
  { map_file:"<ZERO>", addr:0x561bab456000, length:0x1000, prot_flags:"r-xp", file_offset:0x0, device:0, inode:0, data_file:"", data_offset:0x0, file_size:0x1000 }
  { tid:866037, addr:0x561bab456000, length:0x5e }
  { tid:866037, addr:0x561baa684085, length:0xb }
}
{
  real_time:420866.651785 global_time:753, event:`SYSCALLBUF_RESET' tid:866037, ticks:1109725
}
{
  real_time:420866.651830 global_time:754, event:`SYSCALLBUF_FLUSH' tid:866037, ticks:1110046
  { syscall:'gettid', ret:0xd36f5, size:0x10 }
}
{
  real_time:420866.651834 global_time:755, event:`SYSCALL: mmap' (state:ENTERING_SYSCALL) tid:866037, ticks:1110046
rax:0xffffffffffffffda rbx:0xffffffffffffffff rcx:0xffffffffffffffff rdx:0x3 rsi:0xe000 rdi:0x0 rbp:0xe000 rsp:0x7ffe57121940 r8:0xffffffffffffffff r9:0x0 r10:0x22 r11:0x246 r12:0x561baaae9a88 r13:0x7ffe57122260 r14:0x0 r15:0x22 rip:0x561baa683d21 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x9 fs_base:0x7f5420425400 gs_base:0x0
}
{
  real_time:420866.651836 global_time:756, event:`SYSCALLBUF_RESET' tid:866037, ticks:1110046
}
{
  real_time:420866.651867 global_time:757, event:`SYSCALL: mmap' (state:EXITING_SYSCALL) tid:866037, ticks:1110046
rax:0x278a4ad00000 rbx:0xffffffffffffffff rcx:0xffffffffffffffff rdx:0x3 rsi:0xe000 rdi:0x0 rbp:0xe000 rsp:0x7ffe57121940 r8:0xffffffffffffffff r9:0x0 r10:0x22 r11:0x246 r12:0x561baaae9a88 r13:0x7ffe57122260 r14:0x0 r15:0x22 rip:0x561baa683d21 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x9 fs_base:0x7f5420425400 gs_base:0x0
  { map_file:"<ZERO>", addr:0x278a4ad00000, length:0xe000, prot_flags:"rw-p", file_offset:0x0, device:0, inode:0, data_file:"", data_offset:0x0, file_size:0xe000 }
}
{
  real_time:420866.651932 global_time:758, event:`SYSCALL: mmap' (state:ENTERING_SYSCALL) tid:866037, ticks:1110144
rax:0xffffffffffffffda rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x0 rsi:0x801000 rdi:0x0 rbp:0x681fffa0 rsp:0x681ffd40 r8:0xffffffff r9:0x0 r10:0x20022 r11:0x246 r12:0x1000 r13:0x6 r14:0x7ffe57121970 r15:0x802000 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x9 fs_base:0x7f5420425400 gs_base:0x0
}
{
  real_time:420866.651963 global_time:759, event:`SYSCALL: mmap' (state:EXITING_SYSCALL) tid:866037, ticks:1110144
rax:0x5fffff7ff000 rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x0 rsi:0x801000 rdi:0x0 rbp:0x681fffa0 rsp:0x681ffd40 r8:0xffffffff r9:0x0 r10:0x20022 r11:0x246 r12:0x1000 r13:0x6 r14:0x7ffe57121970 r15:0x802000 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x9 fs_base:0x7f5420425400 gs_base:0x0
  { map_file:"<ZERO>", addr:0x5fffff7ff000, length:0x801000, prot_flags:"---p", file_offset:0x0, device:0, inode:0, data_file:"", data_offset:0x0, file_size:0x801000 }
}
{
  real_time:420866.652027 global_time:760, event:`SYSCALLBUF_FLUSH' tid:866037, ticks:1110341
  { syscall:'mprotect', ret:0x0, size:0x10 }
  { start:'0x5fffff800000', size:'800000', prot:rw- }
}
{
  real_time:420866.652185 global_time:761, event:`SYSCALL: clone' (state:ENTERING_SYSCALL) tid:866037, ticks:1110341
rax:0xffffffffffffffda rbx:0x5ffffffff700 rcx:0xffffffffffffffff rdx:0x5ffffffff9d0 rsi:0x5fffffffef30 rdi:0x3d0f00 rbp:0x7ffe57121970 rsp:0x7ffe571218b8 r8:0x5ffffffff700 r9:0x5ffffffff700 r10:0x5ffffffff9d0 r11:0x246 r12:0x7ffe5712196e r13:0x7ffe5712196f r14:0x7ffe57121970 r15:0x5fffffffef40 rip:0x3d3744334125 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x38 fs_base:0x7f5420425400 gs_base:0x0
  { map_file:"<ZERO>", addr:0x7f541fff2000, length:0x200000, prot_flags:"rwxp", file_offset:0x0, device:0, inode:0, data_file:"", data_offset:0x0, file_size:0x0 }
  { tid:866037, addr:0x5ffffffff9d0, length:0x4 }
  { tid:866039, addr:0x5ffffffff9d0, length:0x4 }
  { tid:866039, addr:0x5ffffffff9d0, length:0x4 }
}
{
  real_time:420866.652188 global_time:762, event:`SYSCALLBUF_RESET' tid:866037, ticks:1110341
}
{
  real_time:420866.652281 global_time:763, event:`SYSCALL: set_robust_list' (state:ENTERING_SYSCALL) tid:866039, ticks:145
rax:0xffffffffffffffda rbx:0x5ffffffff700 rcx:0xffffffffffffffff rdx:0xfffffffffffffee8 rsi:0x18 rdi:0x5ffffffff9e0 rbp:0x0 rsp:0x5fffffffee80 r8:0x5ffffffff700 r9:0x5ffffffff700 r10:0xffffffffffffff6d r11:0x246 r12:0x7ffe5712196e r13:0x7ffe5712196f r14:0x7ffe57121970 r15:0x5fffffffef40 rip:0x1adc126cd59a eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x111 fs_base:0x5ffffffff700 gs_base:0x0
}
{
  real_time:420866.652311 global_time:764, event:`SYSCALL: set_robust_list' (state:EXITING_SYSCALL) tid:866039, ticks:145
rax:0x0 rbx:0x5ffffffff700 rcx:0xffffffffffffffff rdx:0xfffffffffffffee8 rsi:0x18 rdi:0x5ffffffff9e0 rbp:0x0 rsp:0x5fffffffee80 r8:0x5ffffffff700 r9:0x5ffffffff700 r10:0xffffffffffffff6d r11:0x246 r12:0x7ffe5712196e r13:0x7ffe5712196f r14:0x7ffe57121970 r15:0x5fffffffef40 rip:0x1adc126cd59a eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x111 fs_base:0x5ffffffff700 gs_base:0x0
}
{
  real_time:420866.652360 global_time:765, event:`SYSCALL: gettid' (state:ENTERING_SYSCALL) tid:866039, ticks:303
rax:0xffffffffffffffda rbx:0x7f54201f1fa0 rcx:0xffffffffffffffff rdx:0x0 rsi:0x0 rdi:0x0 rbp:0x7f54201f1fa0 rsp:0x7f54201f1e20 r8:0x0 r9:0x0 r10:0x0 r11:0x246 r12:0x7ffe5712196e r13:0x7ffe5712196f r14:0x7ffe57121970 r15:0x5fffffffef40 rip:0x70000005 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xba fs_base:0x5ffffffff700 gs_base:0x0
}
{
  real_time:420866.652388 global_time:766, event:`SYSCALL: gettid' (state:EXITING_SYSCALL) tid:866039, ticks:303
rax:0xd36f7 rbx:0x7f54201f1fa0 rcx:0xffffffffffffffff rdx:0x0 rsi:0x0 rdi:0x0 rbp:0x7f54201f1fa0 rsp:0x7f54201f1e20 r8:0x0 r9:0x0 r10:0x0 r11:0x246 r12:0x7ffe5712196e r13:0x7ffe5712196f r14:0x7ffe57121970 r15:0x5fffffffef40 rip:0x70000005 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xba fs_base:0x5ffffffff700 gs_base:0x0
}
{
  real_time:420866.652428 global_time:767, event:`SYSCALL: perf_event_open' (state:ENTERING_SYSCALL) tid:866039, ticks:303
rax:0xffffffffffffffda rbx:0x7f54201f1fa0 rcx:0xffffffffffffffff rdx:0xffffffffffffffff rsi:0x0 rdi:0x7f54201f1e70 rbp:0x7f54201f1fa0 rsp:0x7f54201f1e20 r8:0x0 r9:0x0 r10:0xffffffffffffffff r11:0x246 r12:0x7ffe5712196e r13:0x7f54201f1e70 r14:0xd36f7 r15:0x5fffffffef40 rip:0x70000005 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x12a fs_base:0x5ffffffff700 gs_base:0x0
}
{
  real_time:420866.652468 global_time:768, event:`SYSCALL: perf_event_open' (state:EXITING_SYSCALL) tid:866039, ticks:303
rax:0x3 rbx:0x7f54201f1fa0 rcx:0xffffffffffffffff rdx:0xffffffffffffffff rsi:0x0 rdi:0x7f54201f1e70 rbp:0x7f54201f1fa0 rsp:0x7f54201f1e20 r8:0x0 r9:0x0 r10:0xffffffffffffffff r11:0x246 r12:0x7ffe5712196e r13:0x7f54201f1e70 r14:0xd36f7 r15:0x5fffffffef40 rip:0x70000005 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x12a fs_base:0x5ffffffff700 gs_base:0x0
}
{
  real_time:420866.652526 global_time:769, event:`SYSCALL: fcntl' (state:ENTERING_SYSCALL) tid:866039, ticks:304
rax:0xffffffffffffffda rbx:0x3 rcx:0xffffffffffffffff rdx:0x64 rsi:0x406 rdi:0x3 rbp:0x7f54201f1fa0 rsp:0x7f54201f1dc0 r8:0x0 r9:0x0 r10:0x0 r11:0x246 r12:0x7ffe5712196e r13:0x7f54201f1e70 r14:0xd36f7 r15:0x5fffffffef40 rip:0x70000005 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x48 fs_base:0x5ffffffff700 gs_base:0x0
}
{
  real_time:420866.652561 global_time:770, event:`SYSCALL: fcntl' (state:EXITING_SYSCALL) tid:866039, ticks:304
rax:0x65 rbx:0x3 rcx:0xffffffffffffffff rdx:0x64 rsi:0x406 rdi:0x3 rbp:0x7f54201f1fa0 rsp:0x7f54201f1dc0 r8:0x0 r9:0x0 r10:0x0 r11:0x246 r12:0x7ffe5712196e r13:0x7f54201f1e70 r14:0xd36f7 r15:0x5fffffffef40 rip:0x70000005 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x48 fs_base:0x5ffffffff700 gs_base:0x0
  { tid:866037, addr:0x6fff65ad, length:0x1 }
}
{
  real_time:420866.652608 global_time:771, event:`SYSCALL: rrcall_init_buffers' (state:ENTERING_SYSCALL) tid:866039, ticks:309
rax:0xffffffffffffffda rbx:0x3 rcx:0xffffffffffffffff rdx:0x0 rsi:0x0 rdi:0x7f54201f1e70 rbp:0x7f54201f1fa0 rsp:0x7f54201f1e20 r8:0x0 r9:0x0 r10:0x0 r11:0x246 r12:0x65 r13:0x7f54201f1e70 r14:0xd36f7 r15:0x5fffffffef40 rip:0x70000005 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x3e9 fs_base:0x5ffffffff700 gs_base:0x0
}
[FATAL src/log.cc:444:emergency_debug()] (session doesn't look interactive, aborting emergency debugging)
=== Start rr backtrace:
<rr backtraces not available on this system>
=== End rr backtrace
```

**Comment by khuey** [comment]
If you apply this diff

```diff
diff --git a/src/RecordSession.cc b/src/RecordSession.cc
index 5fd7c8bdf..07f5490ad 100644
--- a/src/RecordSession.cc
+++ b/src/RecordSession.cc
@@ -2147,7 +2147,7 @@ void strip_outer_ld_preload(vector<string>& env) {
 static const MemoryRange asan_shadow(remote_ptr<void>((uintptr_t)0x00007fff7000LL),
                                      remote_ptr<void>((uintptr_t)0x10007fff8000LL));
 static const MemoryRange asan_allocator_reserved(remote_ptr<void>((uintptr_t)0x600000000000LL),
-                                                 remote_ptr<void>((uintptr_t)0x640000000000LL));
+                                                 remote_ptr<void>((uintptr_t)0x640000002000LL));

 // See https://github.com/llvm/llvm-project/blob/main/compiler-rt/lib/tsan/rtl/tsan_platform_posix.cpp
 static const MemoryRange tsan_shadow(remote_ptr<void>((uintptr_t)0x008000000000LL),
```

Does your problem go away?

**Comment by khuey** [comment]
ASAN has an `AdditionalSize` function that's added onto the end of the memory ranges. In 32 bit this is hardcoded to return 0, but in 64 bit it returns 

```cpp
    return RoundUpTo(sizeof(RegionInfo) * kNumClassesRounded,
                     GetPageSizeCached());
```

In one of the uploaded traces there's two extra pages allocated because of this. Since rr doesn't know about them we hand out 0x640000000000 as an address before the main ASAN mapping happens, then the main ASAN mapping obliterates the first mapping, and then the code for the first mapping unmaps what's now at 0x640000000000. Then later, when ASAN tries to access it, we die.

**Comment by khuey** [comment]
I haven't investigated the second one but it's dying in the same 2 page range (just with a different stack), so it's almost certainly the same issue.

**Comment by tysmith** [comment]
I am no longer seeing the ASan crash with the patch applied. I did see the rr assert from above once.

**Comment by khuey** [comment]
Lets file a new issue for the ENOMEM thing.

**Comment by tysmith** [comment]
OK I created issue #3452.
