### ISSUE TITLE
UBSan reports (part 2)

### ISSUE THREAD

**Issue by tysmith** [rr-debugger/rr#3707]
I ran another pass of the tests and ran `rr record` and `rr replay` this time with a clang build, here are the results:

```
/home/user/code/rr/src/TraceStream.cc:672:14: runtime error: null pointer passed as argument 1, which is declared to never be null
```
```
/home/user/code/rr/src/TraceStream.h:186:46: runtime error: load of value 38, which is not a valid value for type 'bool'
```
```
/home/user/code/rr/src/Registers.h:62:39: runtime error: load of value 4294967295, which is not a valid value for type 'rr::SupportedArch'
```
```
/home/user/code/rr/src/Registers.h:58:58: runtime error: load of value 4294967295, which is not a valid value for type 'rr::SupportedArch'
```
```
/home/user/code/rr/src/util.cc:1967:7: runtime error: load of value 4, which is not a valid value for type 'rr::BindCPU'
```
```
/home/user/code/rr/src/util.cc:2025:7: runtime error: load of value 4, which is not a valid value for type 'rr::BindCPU'
```
```
/home/user/code/rr/src/util.cc:2030:20: runtime error: load of value 4, which is not a valid value for type 'rr::BindCPU'
```
```
/home/user/code/rr/src/util.cc:2038:12: runtime error: load of value 4, which is not a valid value for type 'rr::BindCPU'
```
```
/home/user/code/rr/src/kernel_abi.h:1384:55: runtime error: applying non-zero offset 16 to null pointer
    #0 0x55fda4e8d2e3 in rr::BaseArch<(rr::SupportedArch)1, rr::WordSize64Defs>::cmsg_data(rr::BaseArch<(rr::SupportedArch)1, rr::WordSize64Defs>::cmsghdr*) /home/user/code/rr/src/kernel_abi.h:1384:55
    #1 0x55fda4e90378 in rr::fd_message<rr::X64Arch>::remote_cmsgdata() /home/user/code/rr/src/AutoRemoteSyscalls.cc:534:18
    #2 0x55fda4e75949 in long rr::child_recvmsg<rr::X64Arch>(rr::AutoRemoteSyscalls&, int) /home/user/code/rr/src/AutoRemoteSyscalls.cc:604:46
    #3 0x55fda4e7edc6 in int rr::AutoRemoteSyscalls::send_fd_arch<rr::X64Arch>(rr::ScopedFd const&) /home/user/code/rr/src/AutoRemoteSyscalls.cc:733:7
    #4 0x55fda4e6e0bc in rr::AutoRemoteSyscalls::send_fd(rr::ScopedFd const&) /home/user/code/rr/src/AutoRemoteSyscalls.cc:745:3
    #5 0x55fda4e6e217 in rr::AutoRemoteSyscalls::infallible_send_fd_if_alive(rr::ScopedFd const&) /home/user/code/rr/src/AutoRemoteSyscalls.cc:753:18
    #6 0x55fda4db7122 in rr::AddressSpace::map_rr_page(rr::AutoRemoteSyscalls&) /home/user/code/rr/src/AddressSpace.cc:335:27
    #7 0x55fda4dbd915 in rr::AddressSpace::post_exec_syscall(rr::Task*) /home/user/code/rr/src/AddressSpace.cc:636:3
    #8 0x55fda56ae2ac in rr::Task::post_exec_syscall(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/user/code/rr/src/Task.cc:1075:7
    #9 0x55fda5369d32 in rr::process_execve(rr::RecordTask*, rr::TaskSyscallState&) /home/user/code/rr/src/record_syscall.cc:5674:6
    #10 0x55fda53423a3 in void rr::rec_process_syscall_arch<rr::X64Arch>(rr::RecordTask*, rr::TaskSyscallState&) /home/user/code/rr/src/record_syscall.cc:6578:7
    #11 0x55fda525745d in rr::rec_process_syscall_internal(rr::RecordTask*, rr::SupportedArch, rr::TaskSyscallState&) /home/user/code/rr/src/record_syscall.cc:7130:3
    #12 0x55fda5256d85 in rr::rec_process_syscall(rr::RecordTask*) /home/user/code/rr/src/record_syscall.cc:7150:3
    #13 0x55fda51e67ed in rr::RecordSession::syscall_state_changed(rr::RecordTask*, rr::RecordSession::StepState*) /home/user/code/rr/src/RecordSession.cc:1306:11
    #14 0x55fda520346b in rr::RecordSession::record_step() /home/user/code/rr/src/RecordSession.cc:2701:11
    #15 0x55fda51c2a41 in rr::record(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, rr::RecordFlags const&) /home/user/code/rr/src/RecordCommand.cc:711:28
    #16 0x55fda51be973 in rr::RecordCommand::run(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) /home/user/code/rr/src/RecordCommand.cc:874:23
    #17 0x55fda50f5942 in main /home/user/code/rr/src/main.cc:278:19
    #18 0x7f9c66629d8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #19 0x7f9c66629e3f in __libc_start_main csu/../csu/libc-start.c:392:3
    #20 0x55fda4d88964 in _start (/home/user/code/rr/obj/bin/rr+0xc3c964) (BuildId: 7713f1ae134aef9499c2199c5046e5113a162920)
```

**Comment by rocallahan** [comment]
https://github.com/rr-debugger/rr/commit/fe0e8bea3432b8a5f8f594b4d2b9cfdefb9b478e should fix those.

https://github.com/rr-debugger/rr/commit/1fe20ff728b929422a2da2fe37a395f66ab7928a could fix a real problem. I think the other fixes probably fix issues that wouldn't cause problems in practice.

**Comment by tysmith** [comment]
Thanks! Tests now run without triggering any issue.
