### ISSUE TITLE
Unknown ioctl(0x80084e19): type:0x4e nr:0x19 dir:0x2 size:8

### ISSUE THREAD

**Issue by tmcdonell** [rr-debugger/rr#3825]
Using rr @ fd232c6e0ccc332ee23267eb146af897c3e4c906

Complete log:

```
[FATAL src/record_syscall.cc:6603:rec_process_syscall_arch()] 
 (task 36566 (rec:36566) at time 7214)
 -> Assertion `t->regs().syscall_result_signed() == -syscall_state.expect_errno' failed to hold. Expected EINVAL for 'ioctl' but got result 0 (errno SUCCESS); Unknown ioctl(0x80084e19): type:0x4e nr:0x19 dir:0x2 size:8 addr:0xffffb9db61d0
Tail of trace dump:
{
  real_time:5754.332305 global_time:7194, event:`SYSCALL: openat' (state:EXITING_SYSCALL) tid:36566, ticks:8276541
x[0]:0x5 x[1]:0xffffb97e3eb8 x[2]:0x0 x[3]:0x0 x[4]:0xffffd2d77241 x[5]:0xffffd2d77141 x[6]:0x80808080 x[7]:0x4 x[8]:0x38 x[9]:0x5 x[10]:0xa x[11]:0xffffffffffffffff x[12]:0xffffbc336e48 x[13]:0x0 x[14]:0x8b0 x[15]:0x1b34eae3 x[16]:0xffffb97f5010 x[17]:0xffffbdd56db8 x[18]:0xf8cdce95 x[19]:0xffffb97f4000 x[20]:0xffffbdd6f000 x[21]:0xffffb8b54710 x[22]:0x400000023 x[23]:0xffffb97f4000 x[24]:0x0 x[25]:0x23 x[26]:0x2 x[27]:0xffffbdcef2a0 x[28]:0x1 x[29]:0xffffd2d76f70 x[30]:0xffffb97e31d0 sp:0xffffd2d76f70 pc:0xffffbdd56e1c pstate:0x80001000
}
{
  real_time:5754.332345 global_time:7195, event:`SYSCALL: read' (state:ENTERING_SYSCALL) tid:36566, ticks:8276548
x[0]:0x5 x[1]:0xffffd2d77140 x[2]:0x100 x[3]:0xffffb8b53f10 x[4]:0xffffd2d77241 x[5]:0xffffd2d77141 x[6]:0x80808080 x[7]:0x4 x[8]:0x3f x[9]:0x5 x[10]:0xa x[11]:0xffffffffffffffff x[12]:0xffffbc336e48 x[13]:0x0 x[14]:0x8b0 x[15]:0x1b34eae3 x[16]:0xffffb97f5048 x[17]:0xffffbdd56530 x[18]:0xf8cdce95 x[19]:0x5 x[20]:0xffffd2d77150 x[21]:0xffffd2d77140 x[22]:0xffffb8b54710 x[23]:0xffffb97f4000 x[24]:0x0 x[25]:0x23 x[26]:0x2 x[27]:0xffffbdcef2a0 x[28]:0x1 x[29]:0xffffd2d76fd0 x[30]:0xffffb97e31ec sp:0xffffd2d76fd0 pc:0xffffbdd56560 pstate:0x1000
}
{
  real_time:5754.332385 global_time:7196, event:`SYSCALL: read' (state:EXITING_SYSCALL) tid:36566, ticks:8276548
x[0]:0x2 x[1]:0xffffd2d77140 x[2]:0x100 x[3]:0xffffb8b53f10 x[4]:0xffffd2d77241 x[5]:0xffffd2d77141 x[6]:0x80808080 x[7]:0x4 x[8]:0x3f x[9]:0x5 x[10]:0xa x[11]:0xffffffffffffffff x[12]:0xffffbc336e48 x[13]:0x0 x[14]:0x8b0 x[15]:0x1b34eae3 x[16]:0xffffb97f5048 x[17]:0xffffbdd56530 x[18]:0xf8cdce95 x[19]:0x5 x[20]:0xffffd2d77150 x[21]:0xffffd2d77140 x[22]:0xffffb8b54710 x[23]:0xffffb97f4000 x[24]:0x0 x[25]:0x23 x[26]:0x2 x[27]:0xffffbdcef2a0 x[28]:0x1 x[29]:0xffffd2d76fd0 x[30]:0xffffb97e31ec sp:0xffffd2d76fd0 pc:0xffffbdd56560 pstate:0x1000
  { tid:36566, addr:0xffffd2d77140, length:0x2 }
}
{
  real_time:5754.332423 global_time:7197, event:`SYSCALL: close' (state:ENTERING_SYSCALL) tid:36566, ticks:8276553
x[0]:0x5 x[1]:0xffffb8b53f10 x[2]:0x2 x[3]:0xffffb8b53f10 x[4]:0xffffd2d77241 x[5]:0xffffd2d77141 x[6]:0x80808080 x[7]:0x4 x[8]:0x39 x[9]:0x5 x[10]:0xa x[11]:0xffffffffffffffff x[12]:0xffffbc336e48 x[13]:0x0 x[14]:0x8b0 x[15]:0x1b34eae3 x[16]:0xffffb97f5028 x[17]:0xffffbdd56600 x[18]:0xf8cdce95 x[19]:0x5 x[20]:0xffffb8b54710 x[21]:0xffffd2d77140 x[22]:0x400000023 x[23]:0xffffb97f4000 x[24]:0x0 x[25]:0x23 x[26]:0x2 x[27]:0xffffbdcef2a0 x[28]:0x1 x[29]:0xffffd2d76fe0 x[30]:0xffffb97e31fc sp:0xffffd2d76fe0 pc:0xffffbdd5662c pstate:0x1000
}
{
  real_time:5754.332455 global_time:7198, event:`SYSCALL: close' (state:EXITING_SYSCALL) tid:36566, ticks:8276553
x[0]:0x0 x[1]:0xffffb8b53f10 x[2]:0x2 x[3]:0xffffb8b53f10 x[4]:0xffffd2d77241 x[5]:0xffffd2d77141 x[6]:0x80808080 x[7]:0x4 x[8]:0x39 x[9]:0x5 x[10]:0xa x[11]:0xffffffffffffffff x[12]:0xffffbc336e48 x[13]:0x0 x[14]:0x8b0 x[15]:0x1b34eae3 x[16]:0xffffb97f5028 x[17]:0xffffbdd56600 x[18]:0xf8cdce95 x[19]:0x5 x[20]:0xffffb8b54710 x[21]:0xffffd2d77140 x[22]:0x400000023 x[23]:0xffffb97f4000 x[24]:0x0 x[25]:0x23 x[26]:0x2 x[27]:0xffffbdcef2a0 x[28]:0x1 x[29]:0xffffd2d76fe0 x[30]:0xffffb97e31fc sp:0xffffd2d76fe0 pc:0xffffbdd5662c pstate:0x1000
}
{
  real_time:5754.332492 global_time:7199, event:`SYSCALL: openat' (state:ENTERING_SYSCALL) tid:36566, ticks:8276591
x[0]:0xffffffffffffff9c x[1]:0xffffb97e4040 x[2]:0x0 x[3]:0x0 x[4]:0x2002 x[5]:0xffffd2d77141 x[6]:0x80808080 x[7]:0x0 x[8]:0x38 x[9]:0x7 x[10]:0x8 x[11]:0xffffffffffffffff x[12]:0xffffbc336e48 x[13]:0x0 x[14]:0x8b0 x[15]:0x1b34eae3 x[16]:0xffffb97f5010 x[17]:0xffffbdd56db8 x[18]:0xf8cdce95 x[19]:0xffffb97f4000 x[20]:0xffffbdd6f000 x[21]:0xffffb8b54710 x[22]:0x400000023 x[23]:0x2 x[24]:0x0 x[25]:0x23 x[26]:0x2 x[27]:0xffffbdcef2a0 x[28]:0x1 x[29]:0xffffd2d771c0 x[30]:0xffffb97e3cdc sp:0xffffd2d771c0 pc:0xffffbdd56e1c pstate:0x80001000
}
{
  real_time:5754.332548 global_time:7200, event:`SYSCALL: openat' (state:EXITING_SYSCALL) tid:36566, ticks:8276591
x[0]:0xfffffffffffffff3 x[1]:0xffffb97e4040 x[2]:0x0 x[3]:0x0 x[4]:0x2002 x[5]:0xffffd2d77141 x[6]:0x80808080 x[7]:0x0 x[8]:0x38 x[9]:0x7 x[10]:0x8 x[11]:0xffffffffffffffff x[12]:0xffffbc336e48 x[13]:0x0 x[14]:0x8b0 x[15]:0x1b34eae3 x[16]:0xffffb97f5010 x[17]:0xffffbdd56db8 x[18]:0xf8cdce95 x[19]:0xffffb97f4000 x[20]:0xffffbdd6f000 x[21]:0xffffb8b54710 x[22]:0x400000023 x[23]:0x2 x[24]:0x0 x[25]:0x23 x[26]:0x2 x[27]:0xffffbdcef2a0 x[28]:0x1 x[29]:0xffffd2d771c0 x[30]:0xffffb97e3cdc sp:0xffffd2d771c0 pc:0xffffbdd56e1c pstate:0x80001000
}
{
  real_time:5754.332588 global_time:7201, event:`SYSCALL: openat' (state:ENTERING_SYSCALL) tid:36566, ticks:8276612
x[0]:0xffffffffffffff9c x[1]:0xffffb97e41d8 x[2]:0x0 x[3]:0x0 x[4]:0xffffd2d77241 x[5]:0xffffd2d77141 x[6]:0x80808080 x[7]:0x0 x[8]:0x38 x[9]:0x7 x[10]:0x8 x[11]:0xffffffffffffffff x[12]:0xffffbc336e48 x[13]:0x0 x[14]:0x8b0 x[15]:0x1b34eae3 x[16]:0xffffb97f5010 x[17]:0xffffbdd56db8 x[18]:0xf8cdce95 x[19]:0xffffb97f4000 x[20]:0xffffbdd6f000 x[21]:0xffffb8b54710 x[22]:0xffffd2d772a4 x[23]:0x2 x[24]:0x0 x[25]:0x23 x[26]:0x2 x[27]:0xffffd2d772a4 x[28]:0x1 x[29]:0xffffd2d77080 x[30]:0xffffb97e30e8 sp:0xffffd2d77080 pc:0xffffbdd56e1c pstate:0x80001000
}
{
  real_time:5754.332624 global_time:7202, event:`SYSCALL: openat' (state:EXITING_SYSCALL) tid:36566, ticks:8276612
x[0]:0xfffffffffffffffe x[1]:0xffffb97e41d8 x[2]:0x0 x[3]:0x0 x[4]:0xffffd2d77241 x[5]:0xffffd2d77141 x[6]:0x80808080 x[7]:0x0 x[8]:0x38 x[9]:0x7 x[10]:0x8 x[11]:0xffffffffffffffff x[12]:0xffffbc336e48 x[13]:0x0 x[14]:0x8b0 x[15]:0x1b34eae3 x[16]:0xffffb97f5010 x[17]:0xffffbdd56db8 x[18]:0xf8cdce95 x[19]:0xffffb97f4000 x[20]:0xffffbdd6f000 x[21]:0xffffb8b54710 x[22]:0xffffd2d772a4 x[23]:0x2 x[24]:0x0 x[25]:0x23 x[26]:0x2 x[27]:0xffffd2d772a4 x[28]:0x1 x[29]:0xffffd2d77080 x[30]:0xffffb97e30e8 sp:0xffffd2d77080 pc:0xffffbdd56e1c pstate:0x80001000
}
{
  real_time:5754.332661 global_time:7203, event:`SYSCALL: openat' (state:ENTERING_SYSCALL) tid:36566, ticks:8276636
x[0]:0xffffffffffffff9c x[1]:0xffffb97e4210 x[2]:0x0 x[3]:0x0 x[4]:0xffffd2d77241 x[5]:0xffffd2d77141 x[6]:0x80808080 x[7]:0x0 x[8]:0x38 x[9]:0x7 x[10]:0x8 x[11]:0xffffffffffffffff x[12]:0xffffbc336e48 x[13]:0x0 x[14]:0x8b0 x[15]:0x1b34eae3 x[16]:0xffffb97f5010 x[17]:0xffffbdd56db8 x[18]:0xf8cdce95 x[19]:0xffffb97f4000 x[20]:0xffffbdd6f000 x[21]:0xffffb8b54710 x[22]:0xffffd2d772a4 x[23]:0x2 x[24]:0x0 x[25]:0x23 x[26]:0x2 x[27]:0xffffd2d772a4 x[28]:0x1 x[29]:0xffffd2d77080 x[30]:0xffffb97e30e8 sp:0xffffd2d77080 pc:0xffffbdd56e1c pstate:0x80001000
}
{
  real_time:5754.332695 global_time:7204, event:`SYSCALL: openat' (state:EXITING_SYSCALL) tid:36566, ticks:8276636
x[0]:0xfffffffffffffffe x[1]:0xffffb97e4210 x[2]:0x0 x[3]:0x0 x[4]:0xffffd2d77241 x[5]:0xffffd2d77141 x[6]:0x80808080 x[7]:0x0 x[8]:0x38 x[9]:0x7 x[10]:0x8 x[11]:0xffffffffffffffff x[12]:0xffffbc336e48 x[13]:0x0 x[14]:0x8b0 x[15]:0x1b34eae3 x[16]:0xffffb97f5010 x[17]:0xffffbdd56db8 x[18]:0xf8cdce95 x[19]:0xffffb97f4000 x[20]:0xffffbdd6f000 x[21]:0xffffb8b54710 x[22]:0xffffd2d772a4 x[23]:0x2 x[24]:0x0 x[25]:0x23 x[26]:0x2 x[27]:0xffffd2d772a4 x[28]:0x1 x[29]:0xffffd2d77080 x[30]:0xffffb97e30e8 sp:0xffffd2d77080 pc:0xffffbdd56e1c pstate:0x80001000
}
{
  real_time:5754.332730 global_time:7205, event:`SYSCALL: openat' (state:ENTERING_SYSCALL) tid:36566, ticks:8276660
x[0]:0xffffffffffffff9c x[1]:0xffffb97e4240 x[2]:0x0 x[3]:0x0 x[4]:0xffffd2d77241 x[5]:0xffffd2d77141 x[6]:0x80808080 x[7]:0x0 x[8]:0x38 x[9]:0x7 x[10]:0x8 x[11]:0xffffffffffffffff x[12]:0xffffbc336e48 x[13]:0x0 x[14]:0x8b0 x[15]:0x1b34eae3 x[16]:0xffffb97f5010 x[17]:0xffffbdd56db8 x[18]:0xf8cdce95 x[19]:0xffffb97f4000 x[20]:0xffffbdd6f000 x[21]:0xffffb8b54710 x[22]:0xffffd2d772a4 x[23]:0x2 x[24]:0x0 x[25]:0x23 x[26]:0x2 x[27]:0xffffd2d772a4 x[28]:0x1 x[29]:0xffffd2d77080 x[30]:0xffffb97e30e8 sp:0xffffd2d77080 pc:0xffffbdd56e1c pstate:0x80001000
}
{
  real_time:5754.332802 global_time:7206, event:`SYSCALL: openat' (state:EXITING_SYSCALL) tid:36566, ticks:8276660
x[0]:0x5 x[1]:0xffffb97e4240 x[2]:0x0 x[3]:0x0 x[4]:0xffffd2d77241 x[5]:0xffffd2d77141 x[6]:0x80808080 x[7]:0x0 x[8]:0x38 x[9]:0x7 x[10]:0x8 x[11]:0xffffffffffffffff x[12]:0xffffbc336e48 x[13]:0x0 x[14]:0x8b0 x[15]:0x1b34eae3 x[16]:0xffffb97f5010 x[17]:0xffffbdd56db8 x[18]:0xf8cdce95 x[19]:0xffffb97f4000 x[20]:0xffffbdd6f000 x[21]:0xffffb8b54710 x[22]:0xffffd2d772a4 x[23]:0x2 x[24]:0x0 x[25]:0x23 x[26]:0x2 x[27]:0xffffd2d772a4 x[28]:0x1 x[29]:0xffffd2d77080 x[30]:0xffffb97e30e8 sp:0xffffd2d77080 pc:0xffffbdd56e1c pstate:0x80001000
}
{
  real_time:5754.332841 global_time:7207, event:`SYSCALL: read' (state:ENTERING_SYSCALL) tid:36566, ticks:8276667
x[0]:0x5 x[1]:0xffffd2d77140 x[2]:0x100 x[3]:0xffffb8b53f10 x[4]:0xffffd2d77241 x[5]:0xffffd2d77141 x[6]:0x80808080 x[7]:0x0 x[8]:0x3f x[9]:0x7 x[10]:0x8 x[11]:0xffffffffffffffff x[12]:0xffffbc336e48 x[13]:0x0 x[14]:0x8b0 x[15]:0x1b34eae3 x[16]:0xffffb97f5048 x[17]:0xffffbdd56530 x[18]:0xf8cdce95 x[19]:0x5 x[20]:0x5 x[21]:0xffffd2d77140 x[22]:0xffffb8b54710 x[23]:0x2 x[24]:0x0 x[25]:0x23 x[26]:0x2 x[27]:0xffffd2d772a4 x[28]:0x1 x[29]:0xffffd2d770e0 x[30]:0xffffb97e3104 sp:0xffffd2d770e0 pc:0xffffbdd56560 pstate:0x1000
}
{
  real_time:5754.332881 global_time:7208, event:`SYSCALL: read' (state:EXITING_SYSCALL) tid:36566, ticks:8276667
x[0]:0x2 x[1]:0xffffd2d77140 x[2]:0x100 x[3]:0xffffb8b53f10 x[4]:0xffffd2d77241 x[5]:0xffffd2d77141 x[6]:0x80808080 x[7]:0x0 x[8]:0x3f x[9]:0x7 x[10]:0x8 x[11]:0xffffffffffffffff x[12]:0xffffbc336e48 x[13]:0x0 x[14]:0x8b0 x[15]:0x1b34eae3 x[16]:0xffffb97f5048 x[17]:0xffffbdd56530 x[18]:0xf8cdce95 x[19]:0x5 x[20]:0x5 x[21]:0xffffd2d77140 x[22]:0xffffb8b54710 x[23]:0x2 x[24]:0x0 x[25]:0x23 x[26]:0x2 x[27]:0xffffd2d772a4 x[28]:0x1 x[29]:0xffffd2d770e0 x[30]:0xffffb97e3104 sp:0xffffd2d770e0 pc:0xffffbdd56560 pstate:0x1000
  { tid:36566, addr:0xffffd2d77140, length:0x2 }
}
{
  real_time:5754.332916 global_time:7209, event:`SYSCALL: close' (state:ENTERING_SYSCALL) tid:36566, ticks:8276672
x[0]:0x5 x[1]:0xffffb8b53f10 x[2]:0x2 x[3]:0xffffb8b53f10 x[4]:0xffffd2d77241 x[5]:0xffffd2d77141 x[6]:0x80808080 x[7]:0x0 x[8]:0x39 x[9]:0x7 x[10]:0x8 x[11]:0xffffffffffffffff x[12]:0xffffbc336e48 x[13]:0x0 x[14]:0x8b0 x[15]:0x1b34eae3 x[16]:0xffffb97f5028 x[17]:0xffffbdd56600 x[18]:0xf8cdce95 x[19]:0x5 x[20]:0xffffb8b54710 x[21]:0xffffd2d77140 x[22]:0xffffd2d772a4 x[23]:0x2 x[24]:0x0 x[25]:0x23 x[26]:0x2 x[27]:0xffffd2d772a4 x[28]:0x1 x[29]:0xffffd2d770f0 x[30]:0xffffb97e3114 sp:0xffffd2d770f0 pc:0xffffbdd5662c pstate:0x1000
}
{
  real_time:5754.332944 global_time:7210, event:`SYSCALL: close' (state:EXITING_SYSCALL) tid:36566, ticks:8276672
x[0]:0x0 x[1]:0xffffb8b53f10 x[2]:0x2 x[3]:0xffffb8b53f10 x[4]:0xffffd2d77241 x[5]:0xffffd2d77141 x[6]:0x80808080 x[7]:0x0 x[8]:0x39 x[9]:0x7 x[10]:0x8 x[11]:0xffffffffffffffff x[12]:0xffffbc336e48 x[13]:0x0 x[14]:0x8b0 x[15]:0x1b34eae3 x[16]:0xffffb97f5028 x[17]:0xffffbdd56600 x[18]:0xf8cdce95 x[19]:0x5 x[20]:0xffffb8b54710 x[21]:0xffffd2d77140 x[22]:0xffffd2d772a4 x[23]:0x2 x[24]:0x0 x[25]:0x23 x[26]:0x2 x[27]:0xffffd2d772a4 x[28]:0x1 x[29]:0xffffd2d770f0 x[30]:0xffffb97e3114 sp:0xffffd2d770f0 pc:0xffffbdd5662c pstate:0x1000
}
{
  real_time:5754.333002 global_time:7211, event:`SYSCALL: write' (state:ENTERING_SYSCALL) tid:36566, ticks:8278722
x[0]:0x2 x[1]:0xffffd2d74ac8 x[2]:0x29 x[3]:0xffffb8b53f10 x[4]:0x5cb17a6cc1aa302a x[5]:0x1000000100040001 x[6]:0x78 x[7]:0xfffffff4 x[8]:0x40 x[9]:0x0 x[10]:0x0 x[11]:0xffffd2d74948 x[12]:0xc x[13]:0xaaaaec4f9460 x[14]:0x10 x[15]:0x7fffffde x[16]:0x1 x[17]:0xffffbc37ce28 x[18]:0xf8cdce95 x[19]:0x2 x[20]:0xffffd2d74ac8 x[21]:0xffffbc4a24a0 x[22]:0xffffb8b54710 x[23]:0xffffd2d74ac8 x[24]:0x29 x[25]:0xffffd2d77120 x[26]:0xffffbc4a24a0 x[27]:0x2 x[28]:0x1 x[29]:0xffffd2d74870 x[30]:0xffffbc3a2f4c sp:0xffffd2d74870 pc:0xffffbc3f6e10 pstate:0x20001000
}
{
  real_time:5754.333034 global_time:7212, event:`SYSCALL: write' (state:EXITING_SYSCALL) tid:36566, ticks:8278722
x[0]:0x29 x[1]:0xffffd2d74ac8 x[2]:0x29 x[3]:0xffffb8b53f10 x[4]:0x5cb17a6cc1aa302a x[5]:0x1000000100040001 x[6]:0x78 x[7]:0xfffffff4 x[8]:0x40 x[9]:0x0 x[10]:0x0 x[11]:0xffffd2d74948 x[12]:0xc x[13]:0xaaaaec4f9460 x[14]:0x10 x[15]:0x7fffffde x[16]:0x1 x[17]:0xffffbc37ce28 x[18]:0xf8cdce95 x[19]:0x2 x[20]:0xffffd2d74ac8 x[21]:0xffffbc4a24a0 x[22]:0xffffb8b54710 x[23]:0xffffd2d74ac8 x[24]:0x29 x[25]:0xffffd2d77120 x[26]:0xffffbc4a24a0 x[27]:0x2 x[28]:0x1 x[29]:0xffffd2d74870 x[30]:0xffffbc3a2f4c sp:0xffffd2d74870 pc:0xffffbc3f6e10 pstate:0x20001000
}
{
  real_time:5754.333092 global_time:7213, event:`SYSCALL: ioctl' (state:ENTERING_SYSCALL) tid:36566, ticks:8280328
x[0]:0x3 x[1]:0x80084e19 x[2]:0xffffb9db61d0 x[3]:0x0 x[4]:0x0 x[5]:0x0 x[6]:0x80 x[7]:0xff6d6e62686b6872 x[8]:0x1d x[9]:0x2 x[10]:0x0 x[11]:0x0 x[12]:0xffffbc336e48 x[13]:0x0 x[14]:0xffffb9dfe320 x[15]:0x1 x[16]:0xffffbc3fcac0 x[17]:0xffffb9db60b0 x[18]:0xf8cdce95 x[19]:0xffffb9db5000 x[20]:0xffffd2d77250 x[21]:0xffffd2d77254 x[22]:0xffffb9db6000 x[23]:0xffffd2d772c0 x[24]:0xffffbdcf0000 x[25]:0xffffbdcefea0 x[26]:0x0 x[27]:0xffffbdcef2a0 x[28]:0x1 x[29]:0xffffd2d77d60 x[30]:0xffffb9da2c24 sp:0xffffd2d771f0 pc:0xffffbc3fcacc pstate:0x80001000
}
=== Start rr backtrace:
rr(_ZN2rr13dump_rr_stackERNS_8ScopedFdE+0x50)[0xaaaabe7c04e4]
rr(_ZN2rr15emergency_debugEPNS_4TaskE+0x130)[0xaaaabe6a8510]
rr(+0xbd4c8)[0xaaaabe6ad4c8]
rr(+0xbd6ec)[0xaaaabe6ad6ec]
rr(+0xbd72c)[0xaaaabe6ad72c]
rr(+0x132028)[0xaaaabe722028]
rr(_ZN2rr19rec_process_syscallEPNS_10RecordTaskE+0x15c)[0xaaaabe6f5c10]
rr(_ZN2rr13RecordSession21syscall_state_changedEPNS_10RecordTaskEPNS0_9StepStateE+0x364)[0xaaaabe6e6328]
rr(_ZN2rr13RecordSession11record_stepEv+0x55c)[0xaaaabe6e9dac]
rr(_ZN2rr13RecordCommand3runERSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EE+0xa00)[0xaaaabe6def20]
rr(main+0x18c)[0xaaaabe62c5cc]
/lib/aarch64-linux-gnu/libc.so.6(__libc_start_main+0xe8)[0xffff81dc5e10]
rr(+0x3f064)[0xaaaabe62f064]
=== End rr backtrace
```

Attaching the debugging with the supplied command is unfortunately not very helpful (to me):

```
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04.2) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "aarch64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/trevor/Projects/Platform/HiveController/.build/aarch64-unknown-linux-gnu/debug/BuildingSimulatorMain...

warning: Section .debug_names in /home/trevor/Projects/Platform/HiveController/.build/aarch64-unknown-linux-gnu/debug/BuildingSimulatorMain length 6132 does not match section length 13340664, ignoring .debug_names.
Dwarf Error: DW_FORM_strx1 found in non-DWO CU [in module /home/trevor/Projects/Platform/HiveController/.build/aarch64-unknown-linux-gnu/debug/BuildingSimulatorMain]
(No debugging symbols found in /home/trevor/Projects/Platform/HiveController/.build/aarch64-unknown-linux-gnu/debug/BuildingSimulatorMain)
Remote debugging using 127.0.0.1:36566
Reading symbols from /lib/ld-linux-aarch64.so.1...
Reading symbols from /usr/lib/debug/.build-id/69/27993b5ea4304ff398d99d28f36476a848ce21.debug...
0x0000ffffbc3fcacc in _start () from /lib/ld-linux-aarch64.so.1
(gdb) bt
#0  0x0000ffffbc3fcacc in _start () from /lib/ld-linux-aarch64.so.1
#1  0x0000ffffb9da2c24 in ?? ()
#2  0x0000aaaad47d1b78 in ?? ()
#3  0x0000ffffbe56d7a0 in ?? ()
#4  0x0000000000004000 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

This is with a proprietary codebase that I can't share, but I can help track it down if you can give me some pointers.

**Comment by khuey** [comment]
Do you have any clue what ioctl this is? I can't find anything in the kernel that matches. Is there interesting hardware involved?

**Comment by tmcdonell** [comment]
Yep that would be it, there is a NVIDIA GPU attached that it is trying to initialise. Minimal repro:

```c
#include <cuda.h>

int main()
{
  cuInit(0);

  return 0;
}
```

I don't need to debug the CUDA specific code (and certainly nothing that runs on the device), but it would be nice to still use the functionality of rr for the regular host code.

Related #2173
